// AUTO-GENERATED – do not edit, run tools/build_cards.py

export const cardsData = [
  {
    "id": "Val_Red_1",
    "type": "value",
    "nameVi": "Thẻ 1 (Đỏ)",
    "rarity": "common",
    "descriptionVi": "",
    "price": 10,
    "render": "text",
    "value": "1",
    "color": "red",
    "colorHex": "#d91f17",
    "colorName": "Đỏ"
  },
  {
    "id": "Val_Blue_1",
    "type": "value",
    "nameVi": "Thẻ 1 (Xanh dương)",
    "rarity": "common",
    "descriptionVi": "",
    "price": 10,
    "render": "text",
    "value": "1",
    "color": "blue",
    "colorHex": "#1461bd",
    "colorName": "Xanh dương"
  },
  {
    "id": "Val_Green_1",
    "type": "value",
    "nameVi": "Thẻ 1 (Xanh lá)",
    "rarity": "common",
    "descriptionVi": "",
    "price": 10,
    "render": "text",
    "value": "1",
    "color": "green",
    "colorHex": "#268c38",
    "colorName": "Xanh lá"
  },
  {
    "id": "Val_Yellow_1",
    "type": "value",
    "nameVi": "Thẻ 1 (Vàng)",
    "rarity": "common",
    "descriptionVi": "",
    "price": 10,
    "render": "text",
    "value": "1",
    "color": "yellow",
    "colorHex": "#cc7a00",
    "colorName": "Vàng"
  },
  {
    "id": "Val_Red_2",
    "type": "value",
    "nameVi": "Thẻ 2 (Đỏ)",
    "rarity": "common",
    "descriptionVi": "",
    "price": 10,
    "render": "text",
    "value": "2",
    "color": "red",
    "colorHex": "#d91f17",
    "colorName": "Đỏ"
  },
  {
    "id": "Val_Blue_2",
    "type": "value",
    "nameVi": "Thẻ 2 (Xanh dương)",
    "rarity": "common",
    "descriptionVi": "",
    "price": 10,
    "render": "text",
    "value": "2",
    "color": "blue",
    "colorHex": "#1461bd",
    "colorName": "Xanh dương"
  },
  {
    "id": "Val_Green_2",
    "type": "value",
    "nameVi": "Thẻ 2 (Xanh lá)",
    "rarity": "common",
    "descriptionVi": "",
    "price": 10,
    "render": "text",
    "value": "2",
    "color": "green",
    "colorHex": "#268c38",
    "colorName": "Xanh lá"
  },
  {
    "id": "Val_Yellow_2",
    "type": "value",
    "nameVi": "Thẻ 2 (Vàng)",
    "rarity": "common",
    "descriptionVi": "",
    "price": 10,
    "render": "text",
    "value": "2",
    "color": "yellow",
    "colorHex": "#cc7a00",
    "colorName": "Vàng"
  },
  {
    "id": "Val_Red_3",
    "type": "value",
    "nameVi": "Thẻ 3 (Đỏ)",
    "rarity": "common",
    "descriptionVi": "",
    "price": 10,
    "render": "text",
    "value": "3",
    "color": "red",
    "colorHex": "#d91f17",
    "colorName": "Đỏ"
  },
  {
    "id": "Val_Blue_3",
    "type": "value",
    "nameVi": "Thẻ 3 (Xanh dương)",
    "rarity": "common",
    "descriptionVi": "",
    "price": 10,
    "render": "text",
    "value": "3",
    "color": "blue",
    "colorHex": "#1461bd",
    "colorName": "Xanh dương"
  },
  {
    "id": "Val_Green_3",
    "type": "value",
    "nameVi": "Thẻ 3 (Xanh lá)",
    "rarity": "common",
    "descriptionVi": "",
    "price": 10,
    "render": "text",
    "value": "3",
    "color": "green",
    "colorHex": "#268c38",
    "colorName": "Xanh lá"
  },
  {
    "id": "Val_Yellow_3",
    "type": "value",
    "nameVi": "Thẻ 3 (Vàng)",
    "rarity": "common",
    "descriptionVi": "",
    "price": 10,
    "render": "text",
    "value": "3",
    "color": "yellow",
    "colorHex": "#cc7a00",
    "colorName": "Vàng"
  },
  {
    "id": "Val_Red_4",
    "type": "value",
    "nameVi": "Thẻ 4 (Đỏ)",
    "rarity": "common",
    "descriptionVi": "",
    "price": 10,
    "render": "text",
    "value": "4",
    "color": "red",
    "colorHex": "#d91f17",
    "colorName": "Đỏ"
  },
  {
    "id": "Val_Blue_4",
    "type": "value",
    "nameVi": "Thẻ 4 (Xanh dương)",
    "rarity": "common",
    "descriptionVi": "",
    "price": 10,
    "render": "text",
    "value": "4",
    "color": "blue",
    "colorHex": "#1461bd",
    "colorName": "Xanh dương"
  },
  {
    "id": "Val_Green_4",
    "type": "value",
    "nameVi": "Thẻ 4 (Xanh lá)",
    "rarity": "common",
    "descriptionVi": "",
    "price": 10,
    "render": "text",
    "value": "4",
    "color": "green",
    "colorHex": "#268c38",
    "colorName": "Xanh lá"
  },
  {
    "id": "Val_Yellow_4",
    "type": "value",
    "nameVi": "Thẻ 4 (Vàng)",
    "rarity": "common",
    "descriptionVi": "",
    "price": 10,
    "render": "text",
    "value": "4",
    "color": "yellow",
    "colorHex": "#cc7a00",
    "colorName": "Vàng"
  },
  {
    "id": "Val_Red_5",
    "type": "value",
    "nameVi": "Thẻ 5 (Đỏ)",
    "rarity": "common",
    "descriptionVi": "",
    "price": 10,
    "render": "text",
    "value": "5",
    "color": "red",
    "colorHex": "#d91f17",
    "colorName": "Đỏ"
  },
  {
    "id": "Val_Blue_5",
    "type": "value",
    "nameVi": "Thẻ 5 (Xanh dương)",
    "rarity": "common",
    "descriptionVi": "",
    "price": 10,
    "render": "text",
    "value": "5",
    "color": "blue",
    "colorHex": "#1461bd",
    "colorName": "Xanh dương"
  },
  {
    "id": "Val_Green_5",
    "type": "value",
    "nameVi": "Thẻ 5 (Xanh lá)",
    "rarity": "common",
    "descriptionVi": "",
    "price": 10,
    "render": "text",
    "value": "5",
    "color": "green",
    "colorHex": "#268c38",
    "colorName": "Xanh lá"
  },
  {
    "id": "Val_Yellow_5",
    "type": "value",
    "nameVi": "Thẻ 5 (Vàng)",
    "rarity": "common",
    "descriptionVi": "",
    "price": 10,
    "render": "text",
    "value": "5",
    "color": "yellow",
    "colorHex": "#cc7a00",
    "colorName": "Vàng"
  },
  {
    "id": "Val_Red_6",
    "type": "value",
    "nameVi": "Thẻ 6 (Đỏ)",
    "rarity": "common",
    "descriptionVi": "",
    "price": 10,
    "render": "text",
    "value": "6",
    "color": "red",
    "colorHex": "#d91f17",
    "colorName": "Đỏ"
  },
  {
    "id": "Val_Blue_6",
    "type": "value",
    "nameVi": "Thẻ 6 (Xanh dương)",
    "rarity": "common",
    "descriptionVi": "",
    "price": 10,
    "render": "text",
    "value": "6",
    "color": "blue",
    "colorHex": "#1461bd",
    "colorName": "Xanh dương"
  },
  {
    "id": "Val_Green_6",
    "type": "value",
    "nameVi": "Thẻ 6 (Xanh lá)",
    "rarity": "common",
    "descriptionVi": "",
    "price": 10,
    "render": "text",
    "value": "6",
    "color": "green",
    "colorHex": "#268c38",
    "colorName": "Xanh lá"
  },
  {
    "id": "Val_Yellow_6",
    "type": "value",
    "nameVi": "Thẻ 6 (Vàng)",
    "rarity": "common",
    "descriptionVi": "",
    "price": 10,
    "render": "text",
    "value": "6",
    "color": "yellow",
    "colorHex": "#cc7a00",
    "colorName": "Vàng"
  },
  {
    "id": "Val_Red_7",
    "type": "value",
    "nameVi": "Thẻ 7 (Đỏ)",
    "rarity": "common",
    "descriptionVi": "",
    "price": 10,
    "render": "text",
    "value": "7",
    "color": "red",
    "colorHex": "#d91f17",
    "colorName": "Đỏ"
  },
  {
    "id": "Val_Blue_7",
    "type": "value",
    "nameVi": "Thẻ 7 (Xanh dương)",
    "rarity": "common",
    "descriptionVi": "",
    "price": 10,
    "render": "text",
    "value": "7",
    "color": "blue",
    "colorHex": "#1461bd",
    "colorName": "Xanh dương"
  },
  {
    "id": "Val_Green_7",
    "type": "value",
    "nameVi": "Thẻ 7 (Xanh lá)",
    "rarity": "common",
    "descriptionVi": "",
    "price": 10,
    "render": "text",
    "value": "7",
    "color": "green",
    "colorHex": "#268c38",
    "colorName": "Xanh lá"
  },
  {
    "id": "Val_Yellow_7",
    "type": "value",
    "nameVi": "Thẻ 7 (Vàng)",
    "rarity": "common",
    "descriptionVi": "",
    "price": 10,
    "render": "text",
    "value": "7",
    "color": "yellow",
    "colorHex": "#cc7a00",
    "colorName": "Vàng"
  },
  {
    "id": "Val_Red_8",
    "type": "value",
    "nameVi": "Thẻ 8 (Đỏ)",
    "rarity": "common",
    "descriptionVi": "",
    "price": 10,
    "render": "text",
    "value": "8",
    "color": "red",
    "colorHex": "#d91f17",
    "colorName": "Đỏ"
  },
  {
    "id": "Val_Blue_8",
    "type": "value",
    "nameVi": "Thẻ 8 (Xanh dương)",
    "rarity": "common",
    "descriptionVi": "",
    "price": 10,
    "render": "text",
    "value": "8",
    "color": "blue",
    "colorHex": "#1461bd",
    "colorName": "Xanh dương"
  },
  {
    "id": "Val_Green_8",
    "type": "value",
    "nameVi": "Thẻ 8 (Xanh lá)",
    "rarity": "common",
    "descriptionVi": "",
    "price": 10,
    "render": "text",
    "value": "8",
    "color": "green",
    "colorHex": "#268c38",
    "colorName": "Xanh lá"
  },
  {
    "id": "Val_Yellow_8",
    "type": "value",
    "nameVi": "Thẻ 8 (Vàng)",
    "rarity": "common",
    "descriptionVi": "",
    "price": 10,
    "render": "text",
    "value": "8",
    "color": "yellow",
    "colorHex": "#cc7a00",
    "colorName": "Vàng"
  },
  {
    "id": "Val_Red_9",
    "type": "value",
    "nameVi": "Thẻ 9 (Đỏ)",
    "rarity": "common",
    "descriptionVi": "",
    "price": 10,
    "render": "text",
    "value": "9",
    "color": "red",
    "colorHex": "#d91f17",
    "colorName": "Đỏ"
  },
  {
    "id": "Val_Blue_9",
    "type": "value",
    "nameVi": "Thẻ 9 (Xanh dương)",
    "rarity": "common",
    "descriptionVi": "",
    "price": 10,
    "render": "text",
    "value": "9",
    "color": "blue",
    "colorHex": "#1461bd",
    "colorName": "Xanh dương"
  },
  {
    "id": "Val_Green_9",
    "type": "value",
    "nameVi": "Thẻ 9 (Xanh lá)",
    "rarity": "common",
    "descriptionVi": "",
    "price": 10,
    "render": "text",
    "value": "9",
    "color": "green",
    "colorHex": "#268c38",
    "colorName": "Xanh lá"
  },
  {
    "id": "Val_Yellow_9",
    "type": "value",
    "nameVi": "Thẻ 9 (Vàng)",
    "rarity": "common",
    "descriptionVi": "",
    "price": 10,
    "render": "text",
    "value": "9",
    "color": "yellow",
    "colorHex": "#cc7a00",
    "colorName": "Vàng"
  },
  {
    "id": "Val_Pi",
    "type": "value",
    "nameVi": "Thẻ hằng số π (Hằng số Pi)",
    "rarity": "rare",
    "descriptionVi": "",
    "price": 20,
    "render": "text",
    "value": "π",
    "color": "none",
    "colorHex": "#1a1a1a",
    "colorName": "Không màu"
  },
  {
    "id": "Val_Euler",
    "type": "value",
    "nameVi": "Thẻ hằng số e (Hằng số Euler)",
    "rarity": "rare",
    "descriptionVi": "",
    "price": 20,
    "render": "text",
    "value": "e",
    "color": "none",
    "colorHex": "#1a1a1a",
    "colorName": "Không màu"
  },
  {
    "id": "Val_Phi",
    "type": "value",
    "nameVi": "Thẻ hằng số φ (Tỷ lệ vàng)",
    "rarity": "rare",
    "descriptionVi": "",
    "price": 20,
    "render": "text",
    "value": "φ",
    "color": "none",
    "colorHex": "#1a1a1a",
    "colorName": "Không màu"
  },
  {
    "id": "Op_Add",
    "type": "operator",
    "nameVi": "Toán tử Cộng",
    "rarity": "common",
    "descriptionVi": "",
    "price": 15,
    "render": "text",
    "symbol": "+",
    "category": "binary",
    "color": "dark",
    "colorHex": "#1a1a1a",
    "colorName": "Đen"
  },
  {
    "id": "Op_Sub",
    "type": "operator",
    "nameVi": "Toán tử Trừ",
    "rarity": "common",
    "descriptionVi": "",
    "price": 15,
    "render": "text",
    "symbol": "−",
    "category": "binary",
    "color": "dark",
    "colorHex": "#1a1a1a",
    "colorName": "Đen"
  },
  {
    "id": "Op_Mul",
    "type": "operator",
    "nameVi": "Toán tử Nhân",
    "rarity": "common",
    "descriptionVi": "",
    "price": 20,
    "render": "text",
    "symbol": "×",
    "category": "binary",
    "color": "dark",
    "colorHex": "#1a1a1a",
    "colorName": "Đen"
  },
  {
    "id": "Op_Div",
    "type": "operator",
    "nameVi": "Toán tử Chia",
    "rarity": "common",
    "descriptionVi": "",
    "price": 20,
    "render": "text",
    "symbol": "/",
    "category": "binary",
    "color": "dark",
    "colorHex": "#1a1a1a",
    "colorName": "Đen"
  },
  {
    "id": "Op_Sin",
    "type": "operator",
    "nameVi": "Toán tử Sin",
    "rarity": "rare",
    "descriptionVi": "",
    "price": 30,
    "render": "text",
    "symbol": "Sin",
    "category": "unary",
    "color": "dark",
    "colorHex": "#1a1a1a",
    "colorName": "Đen"
  },
  {
    "id": "Op_Cos",
    "type": "operator",
    "nameVi": "Toán tử Cos",
    "rarity": "rare",
    "descriptionVi": "",
    "price": 30,
    "render": "text",
    "symbol": "Cos",
    "category": "unary",
    "color": "dark",
    "colorHex": "#1a1a1a",
    "colorName": "Đen"
  },
  {
    "id": "Op_Tan",
    "type": "operator",
    "nameVi": "Toán tử Tan",
    "rarity": "rare",
    "descriptionVi": "",
    "price": 30,
    "render": "text",
    "symbol": "Tan",
    "category": "unary",
    "color": "dark",
    "colorHex": "#1a1a1a",
    "colorName": "Đen"
  },
  {
    "id": "Op_Ln",
    "type": "operator",
    "nameVi": "Toán tử Ln",
    "rarity": "rare",
    "descriptionVi": "",
    "price": 30,
    "render": "text",
    "symbol": "Ln",
    "category": "unary",
    "color": "dark",
    "colorHex": "#1a1a1a",
    "colorName": "Đen"
  },
  {
    "id": "Op_Sqrt",
    "type": "operator",
    "nameVi": "Toán tử Căn bậc hai",
    "rarity": "rare",
    "descriptionVi": "",
    "price": 30,
    "render": "text",
    "symbol": "√a",
    "category": "unary",
    "color": "dark",
    "colorHex": "#1a1a1a",
    "colorName": "Đen"
  },
  {
    "id": "Op_Abs",
    "type": "operator",
    "nameVi": "Toán tử Giá trị tuyệt đối",
    "rarity": "rare",
    "descriptionVi": "",
    "price": 30,
    "render": "text",
    "symbol": "|a|",
    "category": "unary",
    "color": "dark",
    "colorHex": "#1a1a1a",
    "colorName": "Đen"
  },
  {
    "id": "Op_Ceil",
    "type": "operator",
    "nameVi": "Toán tử Làm tròn lên",
    "rarity": "rare",
    "descriptionVi": "",
    "price": 30,
    "render": "text",
    "symbol": "⌈a⌉",
    "category": "unary",
    "color": "dark",
    "colorHex": "#1a1a1a",
    "colorName": "Đen"
  },
  {
    "id": "Op_Floor",
    "type": "operator",
    "nameVi": "Toán tử Làm tròn xuống",
    "rarity": "rare",
    "descriptionVi": "",
    "price": 30,
    "render": "text",
    "symbol": "⌊a⌋",
    "category": "unary",
    "color": "dark",
    "colorHex": "#1a1a1a",
    "colorName": "Đen"
  },
  {
    "id": "Op_Truncate",
    "type": "operator",
    "nameVi": "Toán tử Cắt thập phân",
    "rarity": "rare",
    "descriptionVi": "",
    "price": 30,
    "render": "text",
    "symbol": "trunc",
    "category": "unary",
    "color": "dark",
    "colorHex": "#1a1a1a",
    "colorName": "Đen"
  },
  {
    "id": "vi_lung",
    "type": "item",
    "nameVi": "Ví lủng",
    "rarity": "epic",
    "descriptionVi": "Khi trang bị: Đưa số <img src=\"assets/icons/coin.webp\" alt=\"Xu\" class=\"card-token-icon\" /> về 0. Khi vào cửa hàng: Mua 1 vật phẩm bất kỳ với giá 0 <img src=\"assets/icons/coin.webp\" alt=\"Xu\" class=\"card-token-icon\" />.",
    "price": 4,
    "legacyFrameIndex": 0,
    "image": "assets/cards/item/vi_lung.webp"
  },
  {
    "id": "hop_urgo",
    "type": "item",
    "nameVi": "Hộp Urgo",
    "rarity": "rare",
    "descriptionVi": "<span style=\"color: #c8f0a8;\">Độ bền</span>: 4. Đỡ số <img src=\"assets/icons/point.webp\" alt=\"Điểm\" class=\"card-token-icon\" /> bị trừ tương đương với độ bền còn lại.",
    "price": 2,
    "legacyFrameIndex": 1,
    "image": "assets/cards/item/hop_urgo.webp"
  },
  {
    "id": "cuc_da",
    "type": "item",
    "nameVi": "Cục đá",
    "rarity": "common",
    "descriptionVi": "Không có tác dụng gì.",
    "price": 1,
    "legacyFrameIndex": 2,
    "image": "assets/cards/item/cuc_da.webp"
  },
  {
    "id": "sach_nang_cao",
    "type": "item",
    "nameVi": "Sách nâng cao",
    "rarity": "rare",
    "descriptionVi": "Mua: -1 <img src=\"assets/icons/point.webp\" alt=\"Điểm\" class=\"card-token-icon\" />. Khi kích hoạt: +1 <img src=\"assets/icons/coin.webp\" alt=\"Xu\" class=\"card-token-icon\" />. Bán: 40% tạo ra Bí kíp nâng cao.",
    "price": 2,
    "legacyFrameIndex": 3,
    "image": "assets/cards/item/sach_nang_cao.webp"
  },
  {
    "id": "bi_kip_nang_cao",
    "type": "item",
    "nameVi": "Bí kíp nâng cao",
    "rarity": "special",
    "descriptionVi": "Khi kích hoạt: x2 <img src=\"assets/icons/coin.webp\" alt=\"Xu\" class=\"card-token-icon\" /> và <img src=\"assets/icons/bcoin.webp\" alt=\"Xu thưởng\" class=\"card-token-icon\" /> nhận được <span style=\"color: #ff9f43;\">(chỉ áp dụng với <img src=\"assets/icons/coin.webp\" alt=\"Xu\" class=\"card-token-icon\" /> và <img src=\"assets/icons/bcoin.webp\" alt=\"Xu thưởng\" class=\"card-token-icon\" /> xếp hạng)</span>.",
    "price": 1,
    "legacyFrameIndex": 4,
    "image": "assets/cards/item/bi_kip_nang_cao.webp"
  },
  {
    "id": "hop_sap_mau",
    "type": "item",
    "nameVi": "Hộp sáp màu",
    "rarity": "common",
    "descriptionVi": "Khi kích hoạt: +<img src=\"assets/icons/coin.webp\" alt=\"Xu\" class=\"card-token-icon\" /> bằng số lá có màu xuất hiện nhiều nhất được đánh ra (tối thiểu +1 <img src=\"assets/icons/coin.webp\" alt=\"Xu\" class=\"card-token-icon\" />).",
    "price": 1,
    "legacyFrameIndex": 5,
    "image": "assets/cards/item/hop_sap_mau.webp"
  },
  {
    "id": "the_tin_dung",
    "type": "item",
    "nameVi": "Thẻ tín dụng",
    "rarity": "rare",
    "descriptionVi": "Mua: Cho phép mua chịu đến tối đa -20 <img src=\"assets/icons/coin.webp\" alt=\"Xu\" class=\"card-token-icon\" />.",
    "price": 2,
    "legacyFrameIndex": 6,
    "image": "assets/cards/item/the_tin_dung.webp"
  },
  {
    "id": "trung_non",
    "type": "item",
    "nameVi": "Trứng non",
    "rarity": "rare",
    "descriptionVi": "Khi kích hoạt: Giá bán +2 <img src=\"assets/icons/coin.webp\" alt=\"Xu\" class=\"card-token-icon\" />.",
    "price": 2,
    "legacyFrameIndex": 7,
    "image": "assets/cards/item/trung_non.webp"
  },
  {
    "id": "trung_vang",
    "type": "item",
    "nameVi": "Trứng Vàng",
    "rarity": "epic",
    "descriptionVi": "Khi kích hoạt: Giá bán +3 <img src=\"assets/icons/coin.webp\" alt=\"Xu\" class=\"card-token-icon\" />.",
    "price": 4,
    "legacyFrameIndex": 8,
    "image": "assets/cards/item/trung_vang.webp"
  },
  {
    "id": "hop_boc_tham",
    "type": "item",
    "nameVi": "Hộp Bốc Thăm",
    "rarity": "rare",
    "descriptionVi": "Khi kích hoạt: Xem người chơi có bao nhiêu lá số 6 trên tay. Khi vào Cửa hàng: Đổi bấy nhiêu lá 6 đó thành bấy nhiêu thẻ Tài liệu ngẫu nhiên.",
    "price": 2,
    "legacyFrameIndex": 9,
    "image": "assets/cards/item/hop_boc_tham.webp"
  },
  {
    "id": "to_do_list",
    "type": "item",
    "nameVi": "To Do List",
    "rarity": "common",
    "descriptionVi": "Khi kích hoạt: +X <img src=\"assets/icons/coin.webp\" alt=\"Xu\" class=\"card-token-icon\" /> nếu thỏa mãn combo. Đổi yêu cầu sau khi check.",
    "price": 1,
    "legacyFrameIndex": 10,
    "image": "assets/cards/item/to_do_list.webp"
  },
  {
    "id": "may_tinh_cam_tay",
    "type": "item",
    "nameVi": "Máy Tính Cầm Tay",
    "rarity": "rare",
    "descriptionVi": "Khi kích hoạt: Với n lá toán tử đã đánh ra, +n <img src=\"assets/icons/coin.webp\" alt=\"Xu\" class=\"card-token-icon\" />.",
    "price": 2,
    "legacyFrameIndex": 11,
    "image": "assets/cards/item/may_tinh_cam_tay.webp"
  },
  {
    "id": "ve_vang",
    "type": "item",
    "nameVi": "Vé vàng",
    "rarity": "epic",
    "descriptionVi": "Khi kích hoạt: Với mỗi lá bài giá trị màu vàng đánh ra, +X <img src=\"assets/icons/coin.webp\" alt=\"Xu\" class=\"card-token-icon\" />.",
    "price": 4,
    "legacyFrameIndex": 12,
    "image": "assets/cards/item/ve_vang.webp"
  },
  {
    "id": "the_qua_tang",
    "type": "item",
    "nameVi": "Thẻ quà tặng",
    "rarity": "rare",
    "descriptionVi": "Khi kích hoạt: +1 <img src=\"assets/icons/coin.webp\" alt=\"Xu\" class=\"card-token-icon\" /> Giá trị bán cho tất cả lá hỗ trợ đang trang bị.",
    "price": 2,
    "legacyFrameIndex": 13,
    "image": "assets/cards/item/the_qua_tang.webp"
  },
  {
    "id": "dong_ho_bam_gio",
    "type": "item",
    "nameVi": "Đồng hồ bấm giờ",
    "rarity": "common",
    "descriptionVi": "Khi kích hoạt: +X <img src=\"assets/icons/bcoin.webp\" alt=\"Xu thưởng\" class=\"card-token-icon\" />.",
    "price": 1,
    "legacyFrameIndex": 14,
    "image": "assets/cards/item/dong_ho_bam_gio.webp"
  },
  {
    "id": "tep_giay_than",
    "type": "item",
    "nameVi": "Tệp Giấy Than",
    "rarity": "rare",
    "descriptionVi": "Khi kích hoạt: 50% hoàn lại gấp đôi số lượng của 1 loại lá (3, 6, hoặc 9) đã đánh ra vào bộ bài bốc.",
    "price": 2,
    "legacyFrameIndex": 15,
    "image": "assets/cards/item/tep_giay_than.webp"
  },
  {
    "id": "sanh",
    "type": "item",
    "nameVi": "Sảnh",
    "rarity": "rare",
    "descriptionVi": "Khi kích hoạt: +1 <img src=\"assets/icons/point.webp\" alt=\"Điểm\" class=\"card-token-icon\" /> nếu đánh ra ít nhất 5 số liên tiếp.",
    "price": 2,
    "legacyFrameIndex": 16,
    "image": "assets/cards/item/sanh.webp"
  },
  {
    "id": "quy_khuyen_hoc",
    "type": "item",
    "nameVi": "Quỹ Khuyến Học",
    "rarity": "common",
    "descriptionVi": "Khi kích hoạt: Nếu đứng bét, +<img src=\"assets/icons/coin.webp\" alt=\"Xu\" class=\"card-token-icon\" /> bằng trung bình cộng số <img src=\"assets/icons/coin.webp\" alt=\"Xu\" class=\"card-token-icon\" /> người khác nhận được.<br /><span style=\"color: #ff9f43;\">chỉ tính <img src=\"assets/icons/coin.webp\" alt=\"Xu\" class=\"card-token-icon\" /> xếp hạng</span>",
    "price": 1,
    "legacyFrameIndex": 17,
    "image": "assets/cards/item/quy_khuyen_hoc.webp"
  },
  {
    "id": "heo_dat_co_khoa",
    "type": "item",
    "nameVi": "Heo đất có khóa",
    "rarity": "rare",
    "descriptionVi": "Khi kích hoạt: Với n lá số 9 trên tay, +n <img src=\"assets/icons/bcoin.webp\" alt=\"Xu thưởng\" class=\"card-token-icon\" /> và +n/2 <img src=\"assets/icons/coin.webp\" alt=\"Xu\" class=\"card-token-icon\" />.",
    "price": 2,
    "legacyFrameIndex": 18,
    "image": "assets/cards/item/heo_dat_co_khoa.webp"
  },
  {
    "id": "chung_nhan_ho_ngheo",
    "type": "item",
    "nameVi": "Chứng nhận hộ nghèo",
    "rarity": "epic",
    "descriptionVi": "Khi kích hoạt: Nếu số <img src=\"assets/icons/coin.webp\" alt=\"Xu\" class=\"card-token-icon\" /> đang âm, +1 <img src=\"assets/icons/point.webp\" alt=\"Điểm\" class=\"card-token-icon\" />.",
    "price": 4,
    "legacyFrameIndex": 19,
    "image": "assets/cards/item/chung_nhan_ho_ngheo.webp"
  },
  {
    "id": "thung",
    "type": "item",
    "nameVi": "Thùng",
    "rarity": "rare",
    "descriptionVi": "Khi kích hoạt: +1 <img src=\"assets/icons/point.webp\" alt=\"Điểm\" class=\"card-token-icon\" /> nếu đánh ra ít nhất 5 lá cùng màu.",
    "price": 2,
    "legacyFrameIndex": 20,
    "image": "assets/cards/item/thung.webp"
  },
  {
    "id": "may_huy_tai_lieu",
    "type": "item",
    "nameVi": "Máy Hủy Tài Liệu",
    "rarity": "rare",
    "descriptionVi": "Khi kích hoạt: Phá hủy vật dụng ở ô bên phải, thêm 3 lá bài giá trị ngẫu nhiên vào bộ bài. Mỗi lá có 30% cơ hội được trang trí.",
    "price": 2,
    "legacyFrameIndex": 21,
    "image": "assets/cards/item/may_huy_tai_lieu.webp"
  },
  {
    "id": "tui_mu",
    "type": "item",
    "nameVi": "Túi mù",
    "rarity": "rare",
    "descriptionVi": "Khi kích hoạt: Tăng giá trị tích lũy thêm 1. Khi đạt 3, tự hủy và thế chỗ bằng 1 vật dụng ngẫu nhiên.",
    "price": 2,
    "legacyFrameIndex": 22,
    "image": "assets/cards/item/tui_mu.webp"
  },
  {
    "id": "ong_nhom",
    "type": "item",
    "nameVi": "Ống nhòm",
    "rarity": "common",
    "descriptionVi": "Khi kích hoạt: Nhận ½ <img src=\"assets/icons/coin.webp\" alt=\"Xu\" class=\"card-token-icon\" /> và ½ <img src=\"assets/icons/bcoin.webp\" alt=\"Xu thưởng\" class=\"card-token-icon\" /> xếp hạng của người ngay trên hạng mình. <span style=\"color: #ff4d4d;\">(chỉ áp dụng với <img src=\"assets/icons/coin.webp\" alt=\"Xu\" class=\"card-token-icon\" /> và <img src=\"assets/icons/bcoin.webp\" alt=\"Xu thưởng\" class=\"card-token-icon\" /> xếp hạng)</span>",
    "price": 1,
    "legacyFrameIndex": 23,
    "image": "assets/cards/item/ong_nhom.webp"
  },
  {
    "id": "ghi_chu",
    "type": "item",
    "nameVi": "Ghi chú",
    "rarity": "common",
    "descriptionVi": "Khi kích hoạt: Nếu kết quả vòng này bằng đúng giá trị lưu giữ từ lượt trước, +X <img src=\"assets/icons/coin.webp\" alt=\"Xu\" class=\"card-token-icon\" /> và +X <img src=\"assets/icons/bcoin.webp\" alt=\"Xu thưởng\" class=\"card-token-icon\" />.",
    "price": 1,
    "legacyFrameIndex": 24,
    "image": "assets/cards/item/ghi_chu.webp"
  },
  {
    "id": "cau_vong",
    "type": "item",
    "nameVi": "Cầu vồng",
    "rarity": "common",
    "descriptionVi": "Khi kích hoạt: +X <img src=\"assets/icons/coin.webp\" alt=\"Xu\" class=\"card-token-icon\" /> nếu đánh ra ít nhất 4 màu khác nhau.",
    "price": 1,
    "legacyFrameIndex": 25,
    "image": "assets/cards/item/cau_vong.webp"
  },
  {
    "id": "jackpot",
    "type": "item",
    "nameVi": "Jackpot",
    "rarity": "common",
    "descriptionVi": "Khi kích hoạt: +X <img src=\"assets/icons/coin.webp\" alt=\"Xu\" class=\"card-token-icon\" /> nếu đánh ra chính xác 3 lá giá trị và đều là số 7.",
    "price": 1,
    "legacyFrameIndex": 26,
    "image": "assets/cards/item/jackpot.webp"
  },
  {
    "id": "day_so",
    "type": "item",
    "nameVi": "Dãy số",
    "rarity": "rare",
    "descriptionVi": "Khi kích hoạt: Duyệt bài trên tay từ trái qua phải, +<img src=\"assets/icons/coin.webp\" alt=\"Xu\" class=\"card-token-icon\" /> bằng độ dài của cấp số cộng dài nhất (công sai > 0).",
    "price": 2,
    "legacyFrameIndex": 27,
    "image": "assets/cards/item/day_so.webp"
  },
  {
    "id": "cong_don",
    "type": "item",
    "nameVi": "Cộng dồn",
    "rarity": "common",
    "descriptionVi": "Khi kích hoạt: +X <img src=\"assets/icons/coin.webp\" alt=\"Xu\" class=\"card-token-icon\" /> nếu có dùng toán tử và tất cả đều là dấu +.",
    "price": 1,
    "legacyFrameIndex": 28,
    "image": "assets/cards/item/cong_don.webp"
  },
  {
    "id": "tru_don",
    "type": "item",
    "nameVi": "Trừ dồn",
    "rarity": "common",
    "descriptionVi": "Khi kích hoạt: +X <img src=\"assets/icons/coin.webp\" alt=\"Xu\" class=\"card-token-icon\" /> nếu có dùng toán tử và tất cả đều là dấu -.",
    "price": 1,
    "legacyFrameIndex": 29,
    "image": "assets/cards/item/tru_don.webp"
  },
  {
    "id": "nhan_don",
    "type": "item",
    "nameVi": "Nhân dồn",
    "rarity": "common",
    "descriptionVi": "Khi kích hoạt: +X <img src=\"assets/icons/coin.webp\" alt=\"Xu\" class=\"card-token-icon\" /> nếu trong lượt chỉ đánh lá dấu nhân.",
    "price": 1,
    "legacyFrameIndex": 30,
    "image": "assets/cards/item/nhan_don.webp"
  },
  {
    "id": "chia_don",
    "type": "item",
    "nameVi": "Chia dồn",
    "rarity": "common",
    "descriptionVi": "Khi kích hoạt: +X <img src=\"assets/icons/coin.webp\" alt=\"Xu\" class=\"card-token-icon\" /> nếu trong lượt chỉ đánh lá dấu chia.",
    "price": 1,
    "legacyFrameIndex": 31,
    "image": "assets/cards/item/chia_don.webp"
  },
  {
    "id": "may_tinh",
    "type": "item",
    "nameVi": "Máy tính",
    "rarity": "common",
    "descriptionVi": "Khi kích hoạt: +X <img src=\"assets/icons/coin.webp\" alt=\"Xu\" class=\"card-token-icon\" /> nếu đánh đủ 4 loại dấu (+, -, x, /).",
    "price": 1,
    "legacyFrameIndex": 32,
    "image": "assets/cards/item/may_tinh.webp"
  },
  {
    "id": "tho_dan",
    "type": "item",
    "nameVi": "Thổ dân",
    "rarity": "common",
    "descriptionVi": "Mỗi lá bài giá trị màu đỏ đánh ra tăng 20% tỷ lệ nhận quà khi kích hoạt (1 lá = 20%, 2 lá = 40%,...). Nếu không đánh lá màu đỏ nào, bị trừ số <img src=\"assets/icons/coin.webp\" alt=\"Xu\" class=\"card-token-icon\" /> bằng đúng số lá giá trị đã đánh. Quà tặng ngẫu nhiên gồm: 50% cơ hội nhận số <img src=\"assets/icons/coin.webp\" alt=\"Xu\" class=\"card-token-icon\" /> bằng số lá giá trị đã đánh; hoặc 50% cơ hội nhận số lá bài giá trị tương ứng vào bộ bài bốc.",
    "price": 1,
    "legacyFrameIndex": 33,
    "image": "assets/cards/item/tho_dan.webp"
  },
  {
    "id": "khe_uoc_quy",
    "type": "item",
    "nameVi": "Khế ước quỷ",
    "rarity": "rare",
    "descriptionVi": "Khi kích hoạt: Đánh 3 lá 6 đỏ -> Nhận x5 <img src=\"assets/icons/coin.webp\" alt=\"Xu\" class=\"card-token-icon\" /> và <img src=\"assets/icons/bcoin.webp\" alt=\"Xu thưởng\" class=\"card-token-icon\" /> của người hạng trên. Không đánh lá đỏ -> Mất toàn bộ <img src=\"assets/icons/coin.webp\" alt=\"Xu\" class=\"card-token-icon\" /> và <img src=\"assets/icons/bcoin.webp\" alt=\"Xu thưởng\" class=\"card-token-icon\" /> của vòng này.<br /><span style=\"color: #ff9f43;\">Chỉ tính thưởng xếp hạng gốc</span>",
    "price": 2,
    "legacyFrameIndex": 34,
    "image": "assets/cards/item/khe_uoc_quy.webp"
  },
  {
    "id": "tetris",
    "type": "item",
    "nameVi": "Tetris",
    "rarity": "common",
    "descriptionVi": "Khi kích hoạt: +X <img src=\"assets/icons/coin.webp\" alt=\"Xu\" class=\"card-token-icon\" /> nếu 2 ô bên cạnh đều có vật dụng.",
    "price": 1,
    "legacyFrameIndex": 35,
    "image": "assets/cards/item/tetris.webp"
  },
  {
    "id": "sisrtet",
    "type": "item",
    "nameVi": "Sisrtet",
    "rarity": "common",
    "descriptionVi": "Khi kích hoạt: +X <img src=\"assets/icons/bcoin.webp\" alt=\"Xu thưởng\" class=\"card-token-icon\" /> nếu 2 ô bên cạnh không có vật dụng.",
    "price": 1,
    "legacyFrameIndex": 36,
    "image": "assets/cards/item/sisrtet.webp"
  },
  {
    "id": "cai_de",
    "type": "item",
    "nameVi": "Cái đe",
    "rarity": "epic",
    "descriptionVi": "Khi kích hoạt: Hợp nhất 3 vật dụng cùng độ hiếm thành 1 vật dụng cao hơn.",
    "price": 4,
    "legacyFrameIndex": 37,
    "image": "assets/cards/item/cai_de.webp"
  },
  {
    "id": "cai_guong",
    "type": "item",
    "nameVi": "Cái gương",
    "rarity": "epic",
    "descriptionVi": "Khi kích hoạt: Biến thành vật dụng nằm bên phải.",
    "price": 4,
    "legacyFrameIndex": 38,
    "image": "assets/cards/item/cai_guong.webp"
  },
  {
    "id": "nam_moc",
    "type": "item",
    "nameVi": "Nấm mốc",
    "rarity": "epic",
    "descriptionVi": "Khi kích hoạt: Tạo 1 bản sao không tác dụng ở ô trống ngẫu nhiên.",
    "price": 4,
    "legacyFrameIndex": 39,
    "image": "assets/cards/item/nam_moc.webp"
  },
  {
    "id": "thuoc_ke",
    "type": "item",
    "nameVi": "Thước kẻ",
    "rarity": "common",
    "descriptionVi": "Khi kích hoạt: +1 <img src=\"assets/icons/coin.webp\" alt=\"Xu\" class=\"card-token-icon\" /> cho mỗi lá vật dụng liên tiếp bên phải.",
    "price": 1,
    "legacyFrameIndex": 40,
    "image": "assets/cards/item/thuoc_ke.webp"
  },
  {
    "id": "hamburger",
    "type": "item",
    "nameVi": "Hamburger",
    "rarity": "rare",
    "descriptionVi": "Khi kích hoạt: Thứ tự màu Vàng-Lục-Đỏ-Vàng: +4 <img src=\"assets/icons/coin.webp\" alt=\"Xu\" class=\"card-token-icon\" /> và tạo 1 bản sao.",
    "price": 2,
    "legacyFrameIndex": 41,
    "image": "assets/cards/item/hamburger.webp"
  },
  {
    "id": "nguoi_nguyen_thuy",
    "type": "item",
    "nameVi": "Người nguyên thủy",
    "rarity": "rare",
    "descriptionVi": "Khi kích hoạt: Mỗi ô vật dụng trống +1 <img src=\"assets/icons/coin.webp\" alt=\"Xu\" class=\"card-token-icon\" /> vào giá bán.",
    "price": 2,
    "legacyFrameIndex": 42,
    "image": "assets/cards/item/nguoi_nguyen_thuy.webp"
  },
  {
    "id": "uranium",
    "type": "item",
    "nameVi": "Uranium",
    "rarity": "epic",
    "descriptionVi": "Khi kích hoạt: x2 <img src=\"assets/icons/coin.webp\" alt=\"Xu\" class=\"card-token-icon\" />, <img src=\"assets/icons/bcoin.webp\" alt=\"Xu thưởng\" class=\"card-token-icon\" /> và <img src=\"assets/icons/point.webp\" alt=\"Điểm\" class=\"card-token-icon\" /> nhận được trong lượt. Cuối lượt tạo Chất thải phóng xạ.",
    "price": 4,
    "legacyFrameIndex": 43,
    "image": "assets/cards/item/uranium.webp"
  },
  {
    "id": "chat_thai_phong_xa",
    "type": "item",
    "nameVi": "Chất thải phóng xạ",
    "rarity": "special",
    "descriptionVi": "Khi kích hoạt: Xóa 1 lá ngẫu nhiên trong bộ bài bốc.",
    "price": 1,
    "legacyFrameIndex": 44,
    "image": "assets/cards/item/chat_thai_phong_xa.webp"
  },
  {
    "id": "ocd",
    "type": "item",
    "nameVi": "OCD",
    "rarity": "common",
    "descriptionVi": "Khi kích hoạt: +X <img src=\"assets/icons/coin.webp\" alt=\"Xu\" class=\"card-token-icon\" /> nếu chỉ đánh chẵn hoặc chỉ đánh lẻ.",
    "price": 1,
    "legacyFrameIndex": 45,
    "image": "assets/cards/item/ocd.webp"
  },
  {
    "id": "camera",
    "type": "item",
    "nameVi": "Camera",
    "rarity": "rare",
    "descriptionVi": "Khi kích hoạt: +X <img src=\"assets/icons/coin.webp\" alt=\"Xu\" class=\"card-token-icon\" /> dựa vào độ hiếm vật dụng đặt cùng ô của người trên hạng.",
    "price": 2,
    "legacyFrameIndex": 46,
    "image": "assets/cards/item/camera.webp"
  },
  {
    "id": "carbon",
    "type": "item",
    "nameVi": "Carbon",
    "rarity": "epic",
    "descriptionVi": "Khi kích hoạt: Tăng giá bán bằng tổng giá bán của tất cả vật dụng độ hiếm khác đang sở hữu.",
    "price": 4,
    "legacyFrameIndex": 47,
    "image": "assets/cards/item/carbon.webp"
  },
  {
    "id": "dejavu",
    "type": "item",
    "nameVi": "Dejavu",
    "rarity": "rare",
    "descriptionVi": "Khi kích hoạt, nếu bài đánh ra giống các lá lượt trước, nhận thưởng cấp độ cao nhất đạt được:<br />- Cùng lá giá trị: +1 <img src=\"assets/icons/coin.webp\" alt=\"Xu\" class=\"card-token-icon\" />.<br />- Cùng lá giá trị và cùng màu: + số <img src=\"assets/icons/coin.webp\" alt=\"Xu\" class=\"card-token-icon\" /> nhận được ở lượt trước.<br />- Cùng lá giá trị, cùng màu và cùng dấu: + số <img src=\"assets/icons/coin.webp\" alt=\"Xu\" class=\"card-token-icon\" /> và <img src=\"assets/icons/bcoin.webp\" alt=\"Xu thưởng\" class=\"card-token-icon\" /> nhận được ở lượt trước.<br />- Cùng lá giá trị, cùng màu, cùng dấu và cùng sự kiện (Event): +1 <img src=\"assets/icons/point.webp\" alt=\"Điểm\" class=\"card-token-icon\" />.\\",
    "price": 2,
    "legacyFrameIndex": 48,
    "image": "assets/cards/item/dejavu.webp"
  },
  {
    "id": "lo_son",
    "type": "item",
    "nameVi": "Lọ sơn",
    "rarity": "common",
    "descriptionVi": "Khi kích hoạt: +1 <img src=\"assets/icons/coin.webp\" alt=\"Xu\" class=\"card-token-icon\" /> cho mỗi lá giá trị được trang trí đã đánh.",
    "price": 1,
    "legacyFrameIndex": 49,
    "image": "assets/cards/item/lo_son.webp"
  },
  {
    "id": "lo_vi_song",
    "type": "item",
    "nameVi": "Lò vi sóng",
    "rarity": "rare",
    "descriptionVi": "Khi kích hoạt: Biến vật dụng bên phải thành 1 vật dụng khác cùng độ hiếm.",
    "price": 2,
    "legacyFrameIndex": 50,
    "image": "assets/cards/item/lo_vi_song.webp"
  },
  {
    "id": "tu_truong",
    "type": "item",
    "nameVi": "Từ trường",
    "rarity": "epic",
    "descriptionVi": "Khi kích hoạt: Các vật dụng nằm giữa 2 lá Từ trường xa nhau nhất sẽ được kích hoạt thêm 1 lần (từ phải sang trái).",
    "price": 4,
    "legacyFrameIndex": 51,
    "image": "assets/cards/item/tu_truong.webp"
  },
  {
    "id": "phu_thuy",
    "type": "item",
    "nameVi": "Phù thủy",
    "rarity": "rare",
    "descriptionVi": "Nếu <img src=\"assets/icons/coin.webp\" alt=\"Xu\" class=\"card-token-icon\" /> gốc > <img src=\"assets/icons/bcoin.webp\" alt=\"Xu thưởng\" class=\"card-token-icon\" /> gốc: Đổi <img src=\"assets/icons/coin.webp\" alt=\"Xu\" class=\"card-token-icon\" /> nhận được vòng này thành <img src=\"assets/icons/bcoin.webp\" alt=\"Xu thưởng\" class=\"card-token-icon\" /> (và ngược lại). Nếu <img src=\"assets/icons/coin.webp\" alt=\"Xu\" class=\"card-token-icon\" /> gốc = <img src=\"assets/icons/bcoin.webp\" alt=\"Xu thưởng\" class=\"card-token-icon\" /> gốc (>= 1): Trừ 1 <img src=\"assets/icons/coin.webp\" alt=\"Xu\" class=\"card-token-icon\" /> và 1 <img src=\"assets/icons/bcoin.webp\" alt=\"Xu thưởng\" class=\"card-token-icon\" /> để đổi lấy +1 <img src=\"assets/icons/point.webp\" alt=\"Điểm\" class=\"card-token-icon\" />.",
    "price": 2,
    "legacyFrameIndex": 52,
    "image": "assets/cards/item/phu_thuy.webp"
  },
  {
    "id": "may_gia_toc_hat",
    "type": "item",
    "nameVi": "Máy gia tốc hạt",
    "rarity": "common",
    "descriptionVi": "Nếu tổng giá trị bài đánh ra > vòng trước: +X <img src=\"assets/icons/coin.webp\" alt=\"Xu\" class=\"card-token-icon\" />. Đồng thời +X <img src=\"assets/icons/bcoin.webp\" alt=\"Xu thưởng\" class=\"card-token-icon\" /> mỗi lần kích hoạt.",
    "price": 1,
    "legacyFrameIndex": 53,
    "image": "assets/cards/item/may_gia_toc_hat.webp"
  },
  {
    "id": "x_item",
    "type": "item",
    "nameVi": "X",
    "rarity": "rare",
    "descriptionVi": "Biến thành lá giá trị ngẫu nhiên. Nếu đánh ra lá giống hệt X: +X <img src=\"assets/icons/coin.webp\" alt=\"Xu\" class=\"card-token-icon\" />. Nếu X là số 0: +1 <img src=\"assets/icons/point.webp\" alt=\"Điểm\" class=\"card-token-icon\" />.",
    "price": 2,
    "legacyFrameIndex": 54,
    "image": "assets/cards/item/x_item.webp"
  },
  {
    "id": "den_giao_thong",
    "type": "item",
    "nameVi": "Đèn giao thông",
    "rarity": "common",
    "descriptionVi": "Mỗi lượt, đèn giao thông sẽ hiện 1 màu bất kỳ (Đỏ, Lục, Vàng). Nếu ở lượt đánh bài, toàn bộ các lá bài giá trị bạn đánh ra đều cùng màu với màu đèn giao thông hiện tại, bạn nhận thêm X <img src=\"assets/icons/coin.webp\" alt=\"Xu\" class=\"card-token-icon\" />. Nếu có ít nhất 1 lá giá trị khác màu đèn chỉ định, bạn sẽ không được nhận thưởng.",
    "price": 1,
    "legacyFrameIndex": 55,
    "image": "assets/cards/item/den_giao_thong.webp"
  },
  {
    "id": "ve_tinh",
    "type": "item",
    "nameVi": "Vệ tinh",
    "rarity": "common",
    "descriptionVi": "Mỗi vòng di chuyển đến 1 ô trống ngẫu nhiên. Nếu di chuyển thành công: +1 Giá bán cho tất cả vật dụng khác.",
    "price": 1,
    "legacyFrameIndex": 56,
    "image": "assets/cards/item/ve_tinh.webp"
  },
  {
    "id": "cai_can",
    "type": "item",
    "nameVi": "Cái cân",
    "rarity": "common",
    "descriptionVi": "Khi kích hoạt: Nếu tổng giá trị bài đánh ra > tổng (<img src=\"assets/icons/coin.webp\" alt=\"Xu\" class=\"card-token-icon\" /> + <img src=\"assets/icons/bcoin.webp\" alt=\"Xu thưởng\" class=\"card-token-icon\" /> + <img src=\"assets/icons/point.webp\" alt=\"Điểm\" class=\"card-token-icon\" />) gốc hiện tại",
    "price": 1,
    "legacyFrameIndex": 57,
    "image": "assets/cards/item/cai_can.webp"
  },
  {
    "id": "bien_gioi",
    "type": "item",
    "nameVi": "Biên giới",
    "rarity": "epic",
    "descriptionVi": "Khi kích hoạt: Hủy bỏ chức năng của tất cả vật dụng bên phải nó. Kích hoạt lại toàn bộ vật dụng bên trái nó (từ phải sang trái).",
    "price": 4,
    "legacyFrameIndex": 58,
    "image": "assets/cards/item/bien_gioi.webp"
  },
  {
    "id": "radium",
    "type": "item",
    "nameVi": "Radium",
    "rarity": "epic",
    "descriptionVi": "Khi kích hoạt: x2 toàn bộ <img src=\"assets/icons/coin.webp\" alt=\"Xu\" class=\"card-token-icon\" />",
    "price": 4,
    "legacyFrameIndex": 59,
    "image": "assets/cards/item/radium.webp"
  },
  {
    "id": "den_hieu",
    "type": "item",
    "nameVi": "Đèn hiệu",
    "rarity": "rare",
    "descriptionVi": "Hiệu ứng phụ thuộc độ hiếm vật dụng bên phải: Thường -> +X <img src=\"assets/icons/coin.webp\" alt=\"Xu\" class=\"card-token-icon\" />. Cao cấp -> +X <img src=\"assets/icons/bcoin.webp\" alt=\"Xu thưởng\" class=\"card-token-icon\" />, +X <img src=\"assets/icons/coin.webp\" alt=\"Xu\" class=\"card-token-icon\" />. Cực phẩm -> +X <span style=\"color: #f5c842;\">SV</span> mọi thẻ. Huyền thoại -> Kích hoạt lại thẻ bên trái.",
    "price": 2,
    "legacyFrameIndex": 61,
    "image": "assets/cards/item/den_hieu.webp"
  },
  {
    "id": "cau_pha_le",
    "type": "item",
    "nameVi": "Cầu pha lê",
    "rarity": "legendary",
    "descriptionVi": "Point x2. Lượt sau không nhận Point thì bị phạt Coin/BCoin vĩnh viễn",
    "price": 8,
    "legacyFrameIndex": 62,
    "image": "assets/cards/item/cau_pha_le.webp"
  },
  {
    "id": "gau_bong",
    "type": "item",
    "nameVi": "Gấu bông",
    "rarity": "common",
    "descriptionVi": "Đứng bét: tăng giá bán",
    "price": 1,
    "legacyFrameIndex": 63,
    "image": "assets/cards/item/gau_bong.webp"
  },
  {
    "id": "dna",
    "type": "item",
    "nameVi": "DNA",
    "rarity": "legendary",
    "descriptionVi": "Biến 1 vật dụng thành lá bên phải nó",
    "price": 8,
    "legacyFrameIndex": 64,
    "image": "assets/cards/item/dna.webp"
  },
  {
    "id": "tetris_legend",
    "type": "item",
    "nameVi": "!TETRIS!",
    "rarity": "rare",
    "descriptionVi": "Tất cả ô là !TETRIS! -> biến mất, +4 point, +2 point multiplier",
    "price": 2,
    "legacyFrameIndex": 65,
    "image": "assets/cards/item/tetris_legend.webp"
  },
  {
    "id": "con_tot",
    "type": "item",
    "nameVi": "Con tốt",
    "rarity": "common",
    "descriptionVi": "Tự di chuyển sang phải nếu như không bị chặn bởi lá bài khác. Kịch đường quay lại, +1 point, có thể tiến hóa",
    "price": 1,
    "legacyFrameIndex": 66,
    "image": "assets/cards/item/con_tot.webp"
  },
  {
    "id": "con_ma",
    "type": "item",
    "nameVi": "Con mã",
    "rarity": "special",
    "descriptionVi": "Di chuyển, nhảy qua 1 vật dụng",
    "price": 1,
    "legacyFrameIndex": 67,
    "image": "assets/cards/item/con_ma.webp"
  },
  {
    "id": "con_tuong",
    "type": "item",
    "nameVi": "Con tượng",
    "rarity": "special",
    "descriptionVi": "Di chuyển, dừng ô lẻ/chẵn thưởng Coin",
    "price": 1,
    "legacyFrameIndex": 68,
    "image": "assets/cards/item/con_tuong.webp"
  },
  {
    "id": "con_xe",
    "type": "item",
    "nameVi": "Con xe",
    "rarity": "special",
    "descriptionVi": "Di chuyển vô hạn ô, dừng trước vật dụng",
    "price": 1,
    "legacyFrameIndex": 69,
    "image": "assets/cards/item/con_xe.webp"
  },
  {
    "id": "con_hau",
    "type": "item",
    "nameVi": "Con hậu",
    "rarity": "special",
    "descriptionVi": "Kết hợp Xe, Mã, Tượng",
    "price": 1,
    "legacyFrameIndex": 70,
    "image": "assets/cards/item/con_hau.webp"
  },
  {
    "id": "con_vua",
    "type": "item",
    "nameVi": "Con vua",
    "rarity": "special",
    "descriptionVi": "Di chuyển phải 1 ô, +1 point. Nếu mất thì nhận thêm point = -1",
    "price": 1,
    "legacyFrameIndex": 71,
    "image": "assets/cards/item/con_vua.webp"
  },
  {
    "id": "gang_tay",
    "type": "item",
    "nameVi": "Găng tay",
    "rarity": "rare",
    "descriptionVi": "Hoán đổi vị trí của vật dụng bên trái và bên phải.",
    "price": 2,
    "legacyFrameIndex": 72,
    "image": "assets/cards/item/gang_tay.webp"
  },
  {
    "id": "bien_cam",
    "type": "item",
    "nameVi": "Biển cấm",
    "rarity": "epic",
    "descriptionVi": "Vô hiệu hóa vật dụng cùng độ hiếm với lá bên phải. Mỗi lượt tăng 0.2 MP (tối đa 2.0).",
    "price": 4,
    "legacyFrameIndex": 73,
    "image": "assets/cards/item/bien_cam.webp"
  },
  {
    "id": "tu_lanh",
    "type": "item",
    "nameVi": "Tủ lạnh",
    "rarity": "legendary",
    "descriptionVi": "Tích trữ số lần kích hoạt lá bên phải. Xả hiệu ứng cho lá bên phải khi bị mất.",
    "price": 8,
    "legacyFrameIndex": 74,
    "image": "assets/cards/item/tu_lanh.webp"
  },
  {
    "id": "to_sell_list",
    "type": "item",
    "nameVi": "To-sell list",
    "rarity": "rare",
    "descriptionVi": "Yêu cầu bán N lá độ hiếm R -> nhận thưởng tương ứng. Đổi yêu cầu mới mỗi lượt.",
    "price": 2,
    "legacyFrameIndex": 75,
    "image": "assets/cards/item/to_sell_list.webp"
  },
  {
    "id": "to_find_list",
    "type": "item",
    "nameVi": "To-find list",
    "rarity": "rare",
    "descriptionVi": "Trang bị đúng vật dụng X: +1 <img src=\"assets/icons/point.webp\" alt=\"Điểm\" class=\"card-token-icon\" />.",
    "price": 2,
    "legacyFrameIndex": 76,
    "image": "assets/cards/item/to_find_list.webp"
  },
  {
    "id": "polonium",
    "type": "item",
    "nameVi": "Polonium",
    "rarity": "epic",
    "descriptionVi": "Khi kích hoạt: x2 số <img src=\"assets/icons/coin.webp\" alt=\"Xu\" class=\"card-token-icon\" />, <img src=\"assets/icons/bcoin.webp\" alt=\"Xu thưởng\" class=\"card-token-icon\" />, <img src=\"assets/icons/point.webp\" alt=\"Điểm\" class=\"card-token-icon\" /> nhận được. Khi mua: phá hủy vĩnh viễn 1 ô vật dụng. Mỗi 5 lần kích hoạt: phá hủy thêm 1 ô.",
    "price": 4,
    "legacyFrameIndex": 77,
    "image": "assets/cards/item/polonium.webp"
  },
  {
    "id": "da_dang",
    "type": "item",
    "nameVi": "Đa dạng",
    "rarity": "epic",
    "descriptionVi": "Đủ 4 độ hiếm vật dụng trong khung: +X <img src=\"assets/icons/point.webp\" alt=\"Điểm\" class=\"card-token-icon\" />.",
    "price": 4,
    "legacyFrameIndex": 78,
    "image": "assets/cards/item/da_dang.webp"
  },
  {
    "id": "bao_tang",
    "type": "item",
    "nameVi": "Bảo tàng",
    "rarity": "rare",
    "descriptionVi": "Khi kích hoạt: +1 Giá bán với mỗi lá hỗ trợ mới nhận được trong lượt.",
    "price": 2,
    "legacyFrameIndex": 79,
    "image": "assets/cards/item/bao_tang.webp"
  },
  {
    "id": "luoi_bieng",
    "type": "item",
    "nameVi": "Lười biếng",
    "rarity": "legendary",
    "descriptionVi": "Khi kích hoạt, với mỗi lá vật dụng đang bị cản kích hoạt trong khung của bạn (không tính các thẻ luôn kích hoạt), tăng thêm 10% tổng số <img src=\"assets/icons/point.webp\" alt=\"Điểm\" class=\"card-token-icon\" /> hiện tại của bạn (lấy phần nguyên).",
    "price": 8,
    "legacyFrameIndex": 81,
    "image": "assets/cards/item/luoi_bieng.webp"
  },
  {
    "id": "may_anh_epic",
    "type": "item",
    "nameVi": "Máy ảnh",
    "rarity": "epic",
    "descriptionVi": "Khi kích hoạt, lá này sẽ biến đổi vĩnh viễn thành lá vật dụng ở cùng vị trí ô của người xếp ngay trên bạn. Nếu ô đó của đối thủ trống, lá này được giữ nguyên.",
    "price": 4,
    "legacyFrameIndex": 82,
    "image": "assets/cards/item/may_anh_epic.webp"
  },
  {
    "id": "nito_long",
    "type": "item",
    "nameVi": "Nitơ lỏng",
    "rarity": "epic",
    "descriptionVi": "Khi đặt ra, toàn bộ <img src=\"assets/icons/coin.webp\" alt=\"Xu\" class=\"card-token-icon\" />, <img src=\"assets/icons/bcoin.webp\" alt=\"Xu thưởng\" class=\"card-token-icon\" /> và <img src=\"assets/icons/point.webp\" alt=\"Điểm\" class=\"card-token-icon\" /> bạn nhận được (từ mọi nguồn) sẽ bị đóng băng và tích lũy vào lá này. Khi bán lá này đi, bạn sẽ nhận lại toàn bộ tài nguyên đã lưu trữ cùng một lúc.",
    "price": 4,
    "legacyFrameIndex": 83,
    "image": "assets/cards/item/nito_long.webp"
  },
  {
    "id": "tang_bang",
    "type": "item",
    "nameVi": "Tảng băng",
    "rarity": "legendary",
    "descriptionVi": "Lá này không có tác dụng gì cho đến khi giá trị bán của nó đạt 0. Khi đó, nó bị hủy và bạn nhận ngẫu nhiên 1 trong 4 phần thưởng: Phủ kim cương 1 lá giá trị trên tay; Nhận 1 lá vật dụng Huyền thoại; x4 giá trị bán các lá vật dụng đang trang bị; Hoặc tạo thêm 1 lá Tảng băng (hủy 1 lá khác nếu khung đã đầy).",
    "price": 8,
    "legacyFrameIndex": 84,
    "image": "assets/cards/item/tang_bang.webp"
  },
  {
    "id": "an_ui",
    "type": "item",
    "nameVi": "An ủi",
    "rarity": "common",
    "descriptionVi": "Khi kích hoạt, nếu bạn không đánh bất kỳ lá bài giá trị nào ở lượt đánh bài (do hết thời gian hoặc bỏ qua), bạn được nhận thêm X <img src=\"assets/icons/coin.webp\" alt=\"Xu\" class=\"card-token-icon\" />.",
    "price": 1,
    "legacyFrameIndex": 85,
    "image": "assets/cards/item/an_ui.webp"
  },
  {
    "id": "linh_hon",
    "type": "item",
    "nameVi": "Linh hồn",
    "rarity": "rare",
    "descriptionVi": "Khi kích hoạt, lá này sẽ cộng cho bạn số <img src=\"assets/icons/coin.webp\" alt=\"Xu\" class=\"card-token-icon\" /> bằng tổng giá trị bán bị giảm đi của tất cả các lá vật dụng đang có trên sân so với lần gần nhất lá Linh hồn này được kích hoạt. Các lá đã bị bán hoặc hủy không được tính.",
    "price": 2,
    "legacyFrameIndex": 86,
    "image": "assets/cards/item/linh_hon.webp"
  },
  {
    "id": "tham_lam",
    "type": "item",
    "nameVi": "Tham lam",
    "rarity": "legendary",
    "descriptionVi": "Khi kích hoạt, đóng băng <img src=\"assets/icons/coin.webp\" alt=\"Xu\" class=\"card-token-icon\" /> thực và cập nhật số <img src=\"assets/icons/coin.webp\" alt=\"Xu\" class=\"card-token-icon\" /> ảo bằng số <img src=\"assets/icons/coin.webp\" alt=\"Xu\" class=\"card-token-icon\" /> bạn đang có (cập nhật nếu <img src=\"assets/icons/coin.webp\" alt=\"Xu\" class=\"card-token-icon\" /> thực cao hơn <img src=\"assets/icons/coin.webp\" alt=\"Xu\" class=\"card-token-icon\" /> ảo). Dùng <img src=\"assets/icons/coin.webp\" alt=\"Xu\" class=\"card-token-icon\" /> ảo để mua sắm trong cửa hàng. Mỗi lượt, giảm 1 giá trị bán của toàn bộ lá vật dụng đang sở hữu. Khi không còn lá nào có giá trị bán > 1, lá này tự động biến mất và <img src=\"assets/icons/coin.webp\" alt=\"Xu\" class=\"card-token-icon\" /> thực hoạt động lại bình thường.",
    "price": 8,
    "legacyFrameIndex": 87,
    "image": "assets/cards/item/tham_lam.webp"
  },
  {
    "id": "do_ki",
    "type": "item",
    "nameVi": "Đố kị",
    "rarity": "epic",
    "descriptionVi": "Khi kích hoạt, nếu tổng giá trị các lá bài đánh ra của người xếp ngay trên bạn lớn hơn của bạn, nhận thêm 10% số <img src=\"assets/icons/point.webp\" alt=\"Điểm\" class=\"card-token-icon\" /> hiện tại của người đó (lấy phần nguyên). Không kích hoạt nếu đứng nhất.",
    "price": 4,
    "legacyFrameIndex": 88,
    "image": "assets/cards/item/do_ki.webp"
  },
  {
    "id": "kieu_ngao",
    "type": "item",
    "nameVi": "Kiêu ngạo",
    "rarity": "legendary",
    "descriptionVi": "Khi kích hoạt, cộng cho bạn số <img src=\"assets/icons/point.webp\" alt=\"Điểm\" class=\"card-token-icon\" /> bằng 10% tổng số <img src=\"assets/icons/point.webp\" alt=\"Điểm\" class=\"card-token-icon\" /> của tất cả người chơi khác (lấy phần nguyên). Với mỗi lá hỗ trợ đang trang bị (không tính lá này), giảm 3% vào hệ số cộng (giảm tối đa về 0%).",
    "price": 8,
    "legacyFrameIndex": 89,
    "image": "assets/cards/item/kieu_ngao.webp"
  },
  {
    "id": "phan_no",
    "type": "item",
    "nameVi": "Phẫn nộ",
    "rarity": "legendary",
    "descriptionVi": "Với mỗi lần bạn không đứng nhất ở lượt tính điểm, lá này cộng thêm % tổng số <img src=\"assets/icons/point.webp\" alt=\"Điểm\" class=\"card-token-icon\" /> của các người chơi khác cho bạn. Mỗi lần kích hoạt, hệ số cộng tăng thêm 3% (tối đa đạt 50%).",
    "price": 8,
    "legacyFrameIndex": 90,
    "image": "assets/cards/item/phan_no.webp"
  },
  {
    "id": "sac_duc",
    "type": "item",
    "nameVi": "Sắc dục",
    "rarity": "epic",
    "descriptionVi": "Khi kích hoạt, chọn người xếp trên bạn (nếu đứng nhất, chọn người xếp dưới). Tăng thêm <img src=\"assets/icons/point.webp\" alt=\"Điểm\" class=\"card-token-icon\" /> bằng 10% số <img src=\"assets/icons/point.webp\" alt=\"Điểm\" class=\"card-token-icon\" /> của người đó với mỗi lá Huyền thoại họ trang bị (tối đa 20%). Nếu họ không có lá Huyền thoại, tăng 5% với mỗi lá Cực phẩm (tối đa 10%).",
    "price": 4,
    "legacyFrameIndex": 91,
    "image": "assets/cards/item/sac_duc.webp"
  },
  {
    "id": "tham_an",
    "type": "item",
    "nameVi": "Tham ăn",
    "rarity": "legendary",
    "descriptionVi": "Ở cửa hàng trước, các lá vật dụng bạn bán sẽ không nhận được <img src=\"assets/icons/coin.webp\" alt=\"Xu\" class=\"card-token-icon\" />. Đổi lại, khi kích hoạt, mỗi lá đã bán sẽ cộng cho bạn 2% tổng số <img src=\"assets/icons/point.webp\" alt=\"Điểm\" class=\"card-token-icon\" /> của tất cả người chơi khác (lấy phần nguyên). Số % không cộng dồn qua các lượt.",
    "price": 8,
    "legacyFrameIndex": 92,
    "image": "assets/cards/item/tham_an.webp"
  },
  {
    "id": "lang_kinh_hoi_tu",
    "type": "item",
    "nameVi": "Lăng kính hội tụ",
    "rarity": "epic",
    "descriptionVi": "Khi kích hoạt, nó sẽ sao chép và kích hoạt lại chức năng của tất cả các lá vật dụng có khả năng kích hoạt (không tính thẻ luôn kích hoạt) trong khung của bạn theo thứ tự từ phải qua trái.",
    "price": 4,
    "legacyFrameIndex": 93,
    "image": "assets/cards/item/lang_kinh_hoi_tu.webp"
  },
  {
    "id": "adrenaline",
    "type": "item",
    "nameVi": "Adrenaline",
    "rarity": "legendary",
    "descriptionVi": "Luân phiên 2 trạng thái: Sẵn sàng và Chờ. Ở trạng thái Sẵn sàng: Nhân 3 số <img src=\"assets/icons/coin.webp\" alt=\"Xu\" class=\"card-token-icon\" />, <img src=\"assets/icons/bcoin.webp\" alt=\"Xu thưởng\" class=\"card-token-icon\" />, <img src=\"assets/icons/point.webp\" alt=\"Điểm\" class=\"card-token-icon\" /> nhận được trong lượt. Nhân 3 giá trị bán của các lá vật dụng hiện tại. Sau đó, kích hoạt lại các lá nằm bên trái nó (từ phải sang trái). Xong việc sẽ chuyển sang trạng thái Chờ (không kích hoạt gì).",
    "price": 8,
    "legacyFrameIndex": 94,
    "image": "assets/cards/item/adrenaline.webp"
  },
  {
    "id": "nen_tang_vung_vang",
    "type": "course",
    "nameVi": "Nền Tảng Vững Vàng",
    "rarity": "rare",
    "descriptionVi": "Bảo đảm số Point của bản thân không bao giờ bị giảm.",
    "price": 3,
    "image": "assets/cards/course/nen_tang_vung_vang.webp"
  },
  {
    "id": "san_ve_quay_thuong",
    "type": "course",
    "nameVi": "Săn vé quay thưởng",
    "rarity": "common",
    "descriptionVi": "Tặng 1 lượt Reroll miễn phí mỗi khi vào Cửa hàng.",
    "price": 1,
    "image": "assets/cards/course/san_ve_quay_thuong.webp"
  },
  {
    "id": "giam_dinh_chuyen_sau",
    "type": "course",
    "nameVi": "Giám Định Chuyên Sâu",
    "rarity": "common",
    "descriptionVi": "Có 50% cơ hội xuất hiện thêm túi trang trí hoặc nhãn dán khi mở gói bài bất kỳ trong Cửa hàng.",
    "price": 1,
    "image": "assets/cards/course/giam_dinh_chuyen_sau.webp"
  },
  {
    "id": "ky_nang_da_nhiem_1",
    "type": "course",
    "nameVi": "Kỹ Năng Đa Nhiệm I",
    "rarity": "rare",
    "descriptionVi": "Tăng giới hạn bài giá trị cầm trên tay lên tối đa 9 lá (không tính lá có nhãn dán Ẩn dấu).",
    "price": 3,
    "image": "assets/cards/course/ky_nang_da_nhiem_1.webp"
  },
  {
    "id": "san_hoc_bong",
    "type": "course",
    "nameVi": "Săn Học Bổng",
    "rarity": "legendary",
    "descriptionVi": "Đồng giá toàn bộ nhãn dán, túi trang trí và gói của chúng trong shop thành 1 Coin.",
    "price": 10,
    "image": "assets/cards/course/san_hoc_bong.webp"
  },
  {
    "id": "my_thuat_co_ban",
    "type": "course",
    "nameVi": "Mỹ Thuật Cơ Bản",
    "rarity": "common",
    "descriptionVi": "Khi tính điểm, lá Đỏ và Vàng coi là cùng chất, lá Lục và Lam coi là cùng chất.",
    "price": 1,
    "image": "assets/cards/course/my_thuat_co_ban.webp"
  },
  {
    "id": "ky_nang_da_nhiem_2",
    "type": "course",
    "nameVi": "Kỹ Năng Đa Nhiệm II",
    "rarity": "rare",
    "descriptionVi": "Tăng số lượng bài dấu tối đa có thể đặt ở khung lên 5 lá.",
    "price": 3,
    "image": "assets/cards/course/ky_nang_da_nhiem_2.webp"
  },
  {
    "id": "ky_nang_da_nhiem_3",
    "type": "course",
    "nameVi": "Kỹ Năng Đa Nhiệm III",
    "rarity": "epic",
    "descriptionVi": "Tăng số lượng bài vật dụng tối đa có thể đặt ở khung lên 5 lá.",
    "price": 6,
    "image": "assets/cards/course/ky_nang_da_nhiem_3.webp"
  },
  {
    "id": "thi_trac_nghiem_mu",
    "type": "course",
    "nameVi": "Thi Trắc Nghiệm Mù",
    "rarity": "rare",
    "descriptionVi": "Không thể nhìn thấy giá trị mục tiêu. Nếu là người duy nhất đứng nhất trong lượt, toàn bộ Coin và BCoin sẽ chuyển đổi thành Point.",
    "price": 3,
    "image": "assets/cards/course/thi_trac_nghiem_mu.webp"
  },
  {
    "id": "kinh_te_tuan_hoan",
    "type": "course",
    "nameVi": "Kinh Tế Tuần Hoàn",
    "rarity": "epic",
    "descriptionVi": "Vật dụng bị bán sẽ không thể xuất hiện hoặc mua lại trong ván. Cứ mỗi 4 vật dụng bị bán, hệ số nhân Point tăng thêm 0.5.",
    "price": 6,
    "image": "assets/cards/course/kinh_te_tuan_hoan.webp"
  },
  {
    "id": "ren_luyen_ap_luc_cao",
    "type": "course",
    "nameVi": "Rèn Luyện Áp Lực Cao",
    "rarity": "epic",
    "descriptionVi": "Mỗi lượt tự động hủy ngẫu nhiên 2 lá giá trị và 1 lá dấu trên tay (hoặc 3 lá giá trị). Đổi lại, nhận thêm +0.4 hệ số nhân Point mỗi lượt.",
    "price": 6,
    "image": "assets/cards/course/ren_luyen_ap_luc_cao.webp"
  },
  {
    "id": "gui_tiet_kiem_co_dinh",
    "type": "course",
    "nameVi": "Gửi Tiết Kiệm Cố Định",
    "rarity": "legendary",
    "descriptionVi": "Đặt và cố định số Coin hiện có thành 20 Coin (không thể thay đổi). Mọi nguồn Coin nhận được sau đó tự động chuyển đổi thành BCoin.",
    "price": 10,
    "image": "assets/cards/course/gui_tiet_kiem_co_dinh.webp"
  },
  {
    "id": "chieu_co_cham_diem",
    "type": "course",
    "nameVi": "Chiếu Cố Chấm Điểm",
    "rarity": "rare",
    "descriptionVi": "Tự động làm tròn lên số nguyên gần nhất đối với mọi con số thập phân do hệ thống trả về (Point, Coin, BCoin...).",
    "price": 3,
    "image": "assets/cards/course/chieu_co_cham_diem.webp"
  },
  {
    "id": "luat_su_bien_ho",
    "type": "course",
    "nameVi": "Luật Sư Biện Hộ",
    "rarity": "common",
    "descriptionVi": "Có 30% cơ hội lấy miễn phí một gói bài khi không đủ tiền mua. Thất bại sẽ bị cấm mua hàng và thao tác trong sảnh ở lượt tiếp theo.",
    "price": 1,
    "image": "assets/cards/course/luat_su_bien_ho.webp"
  },
  {
    "id": "xac_suat_thong_ke",
    "type": "course",
    "nameVi": "Xác Suất Thống Kê",
    "rarity": "epic",
    "descriptionVi": "Nhân đôi tỷ lệ kích hoạt cho khả năng tốt nhất của các thẻ vật dụng có chứa hiệu ứng xác suất (tối đa 90%).",
    "price": 6,
    "image": "assets/cards/course/xac_suat_thong_ke.webp"
  },
  {
    "id": "quan_ly_diem_ren_luyen",
    "type": "course",
    "nameVi": "Quản Lý Điểm Rèn Luyện",
    "rarity": "rare",
    "descriptionVi": "Hạng nhất nhận 1 Điểm danh vọng, đủ 5 điểm đổi thành +1 Point. Đứng bét trừ 1 Điểm danh vọng, chạm -5 điểm đổi thành -1 Point.",
    "price": 3,
    "image": "assets/cards/course/quan_ly_diem_ren_luyen.webp"
  },
  {
    "id": "tot_nghiep_xuat_sac",
    "type": "course",
    "nameVi": "Tốt Nghiệp Xuất Sắc",
    "rarity": "special",
    "descriptionVi": "Xuất hiện khi sở hữu cả 4 khóa học: Khởi Nghiệp Vốn Ít, Thi Trắc Nghiệm Mù, Kinh Tế Tuần Hoàn, Rèn Luyện Áp Lực Cao (tự hủy 4 khóa học này khi mua). Mọi vật dụng nhận được sau đó luôn là Cực phẩm hoặc Huyền thoại với tỷ lệ 50% - 50%.",
    "price": 1,
    "image": "assets/cards/course/tot_nghiep_xuat_sac.webp"
  },
  {
    "id": "ao_thuat_cap_toc",
    "type": "course",
    "nameVi": "Ảo Thuật Cấp Tốc",
    "rarity": "rare",
    "descriptionVi": "Bắt đầu lượt mới, lấp đầy khung bằng các vật dụng tạm thời không thể bán/hủy và thay mới mỗi lượt (tỷ lệ: 1% Huyền thoại, 69% Cực phẩm, 20% Cao cấp, 10% Thường).",
    "price": 3,
    "image": "assets/cards/course/ao_thuat_cap_toc.webp"
  },
  {
    "id": "nghien_cuu_vat_lieu",
    "type": "course",
    "nameVi": "Nghiên Cứu Vật Liệu",
    "rarity": "epic",
    "descriptionVi": "Mỗi lượt tự động tạo 1 vật dụng chưa từng sở hữu vào ô trống trong khung. Hiệu ứng dừng hoạt động khi đã khám phá hết toàn bộ vật dụng.",
    "price": 6,
    "image": "assets/cards/course/nghien_cuu_vat_lieu.webp"
  },
  {
    "id": "khoi_nghiep_von_it",
    "type": "course",
    "nameVi": "Khởi Nghiệp Vốn Ít",
    "rarity": "epic",
    "descriptionVi": "Chỉ chứa vật dụng Thường hoặc Cao cấp: sau 5 lượt nhận +0.5 hệ số nhân Point, duy trì tiếp 10 lượt nhận thêm +0.5 (tối đa +2.0).",
    "price": 6,
    "image": "assets/cards/course/khoi_nghiep_von_it.webp"
  },
  {
    "id": "quy_trinh_quan_ly",
    "type": "course",
    "nameVi": "Quy Trình Quản Lý",
    "rarity": "common",
    "descriptionVi": "Thay đổi thứ tự kích hoạt vật dụng: ưu tiên kích hoạt theo độ hiếm từ cao xuống thấp (cùng độ hiếm kích hoạt từ trái qua phải).",
    "price": 1,
    "image": "assets/cards/course/quy_trinh_quan_ly.webp"
  },
  {
    "id": "loi_nguyen",
    "type": "course",
    "nameVi": "Lời nguyền",
    "rarity": "special",
    "descriptionVi": "Khi 1 lá hỗ trợ kích hoạt, giá trị bán của lá đó giảm đi x/2 (lấy phần nguyên).",
    "price": 1,
    "image": "assets/cards/course/loi_nguyen.webp"
  },
  {
    "id": "on_thi_cap_toc",
    "type": "course",
    "nameVi": "Ôn Thi Cấp Tốc",
    "rarity": "rare",
    "descriptionVi": "Mỗi lượt không đạt BCoin xếp hạng nhất: +0.1 Hệ số Nhân <img src=\"assets/icons/bcoin.webp\" alt=\"Xu thưởng\" class=\"card-token-icon\" />.",
    "price": 3,
    "image": "assets/cards/course/on_thi_cap_toc.webp"
  },
  {
    "id": "toan_hoc_but_pha",
    "type": "course",
    "nameVi": "Toán Học Bứt Phá",
    "rarity": "common",
    "descriptionVi": "30% khi mở gói bài toán tử được chọn thêm 1 thẻ bài dấu.",
    "price": 1,
    "image": "assets/cards/course/toan_hoc_but_pha.webp"
  },
  {
    "id": "phan_doan_nhu_than",
    "type": "course",
    "nameVi": "Phán Đoán Như Thần",
    "rarity": "rare",
    "descriptionVi": "Mua gói cấp thấp được ≥2 thẻ cấp cao hơn: +0.2 Hệ số Nhân <img src=\"assets/icons/coin.webp\" alt=\"Xu\" class=\"card-token-icon\" /> (tối đa +2.0).",
    "price": 3,
    "image": "assets/cards/course/phan_doan_nhu_than.webp"
  },
  {
    "id": "quan_ly_chi_tieu",
    "type": "course",
    "nameVi": "Quản Lý Chi Tiêu",
    "rarity": "common",
    "descriptionVi": "Mỗi lượt cửa hàng chỉ mua tối đa 2 món: +x <img src=\"assets/icons/coin.webp\" alt=\"Xu\" class=\"card-token-icon\" />.",
    "price": 1,
    "image": "assets/cards/course/quan_ly_chi_tieu.webp"
  },
  {
    "id": "an_toan_tai_san",
    "type": "course",
    "nameVi": "An toàn tài sản",
    "rarity": "rare",
    "descriptionVi": "Giá trị bán của tất cả lá vật dụng đang sử dụng không thể thay đổi và ngăn tất cả các lá bị biến mất dưới bất kì hình thức nào trừ bán.",
    "price": 3,
    "image": "assets/cards/course/an_toan_tai_san.webp"
  },
  {
    "id": "777",
    "type": "document",
    "nameVi": "777",
    "rarity": "common",
    "descriptionVi": "Đổi giá trị lá mục tiêu thành 777.",
    "price": 1,
    "artworkFrameIndex": 0,
    "image": "assets/cards/document/777.webp"
  },
  {
    "id": "qua_da",
    "type": "document",
    "nameVi": "Quá đà",
    "rarity": "legendary",
    "descriptionVi": "Nhân 4 lần số lá đang có trên tay và trong bộ bài bốc.",
    "price": 8,
    "artworkFrameIndex": 1,
    "image": "assets/cards/document/qua_da.webp"
  },
  {
    "id": "doi_dau",
    "type": "document",
    "nameVi": "Đổi dấu",
    "rarity": "rare",
    "descriptionVi": "Đổi dấu giá trị của lá mục tiêu.",
    "price": 2,
    "artworkFrameIndex": 2,
    "image": "assets/cards/document/doi_dau.webp"
  },
  {
    "id": "thanh_tay",
    "type": "document",
    "nameVi": "Thanh Tẩy",
    "rarity": "common",
    "descriptionVi": "Loại bỏ trang trí khỏi lá mục tiêu.",
    "price": 1,
    "artworkFrameIndex": 3,
    "image": "assets/cards/document/thanh_tay.webp"
  },
  {
    "id": "muc",
    "type": "document",
    "nameVi": "Mực",
    "rarity": "rare",
    "descriptionVi": "Đổi giá trị lá mục tiêu thành giá trị lá bên phải.",
    "price": 2,
    "artworkFrameIndex": 4,
    "image": "assets/cards/document/muc.webp"
  },
  {
    "id": "lang_kinh_hon_mang",
    "type": "document",
    "nameVi": "Lăng Kính Hỗn Mang",
    "rarity": "rare",
    "descriptionVi": "Đổi màu ngẫu nhiên toàn bộ lá giá trị đang cầm trên tay.",
    "price": 2,
    "artworkFrameIndex": 5,
    "image": "assets/cards/document/lang_kinh_hon_mang.webp"
  },
  {
    "id": "chan_hoa",
    "type": "document",
    "nameVi": "Chẵn Hóa",
    "rarity": "common",
    "descriptionVi": "Biến lá mục tiêu thành giá trị chẵn gần nhất.",
    "price": 1,
    "artworkFrameIndex": 6,
    "image": "assets/cards/document/chan_hoa.webp"
  },
  {
    "id": "so_7_may_man",
    "type": "document",
    "nameVi": "Số 7 may mắn",
    "rarity": "epic",
    "descriptionVi": "Trang trí Lucky cho các lá số 7 chưa có trang trí.",
    "price": 4,
    "artworkFrameIndex": 7,
    "image": "assets/cards/document/so_7_may_man.webp"
  },
  {
    "id": "tru_di_cuu_toc",
    "type": "document",
    "nameVi": "Tru di cửu tộc",
    "rarity": "rare",
    "descriptionVi": "Đổi toàn bộ lá số 9 trong bộ bài bốc thành số 1.",
    "price": 2,
    "artworkFrameIndex": 8,
    "image": "assets/cards/document/tru_di_cuu_toc.webp"
  },
  {
    "id": "mat_gia",
    "type": "document",
    "nameVi": "Mất giá",
    "rarity": "rare",
    "descriptionVi": "Giảm giá trị lá mục tiêu đi 1.",
    "price": 2,
    "artworkFrameIndex": 9,
    "image": "assets/cards/document/mat_gia.webp"
  },
  {
    "id": "lam",
    "type": "document",
    "nameVi": "Lam",
    "rarity": "common",
    "descriptionVi": "Đổi màu lá mục tiêu thành lam.",
    "price": 1,
    "artworkFrameIndex": 10,
    "image": "assets/cards/document/lam.webp"
  },
  {
    "id": "do",
    "type": "document",
    "nameVi": "Đỏ",
    "rarity": "common",
    "descriptionVi": "Đổi màu lá mục tiêu thành đỏ.",
    "price": 1,
    "artworkFrameIndex": 11,
    "image": "assets/cards/document/do.webp"
  },
  {
    "id": "vang",
    "type": "document",
    "nameVi": "Vàng",
    "rarity": "common",
    "descriptionVi": "Đổi màu lá mục tiêu thành vàng.",
    "price": 1,
    "artworkFrameIndex": 12,
    "image": "assets/cards/document/vang.webp"
  },
  {
    "id": "luc",
    "type": "document",
    "nameVi": "Lục",
    "rarity": "common",
    "descriptionVi": "Đổi màu lá mục tiêu thành lục.",
    "price": 1,
    "artworkFrameIndex": 13,
    "image": "assets/cards/document/luc.webp"
  },
  {
    "id": "co_3",
    "type": "document",
    "nameVi": "Có 3",
    "rarity": "common",
    "descriptionVi": "Đổi giá trị lá mục tiêu thành 3.",
    "price": 1,
    "artworkFrameIndex": 14,
    "image": "assets/cards/document/co_3.webp"
  },
  {
    "id": "tai_cau_truc",
    "type": "document",
    "nameVi": "Tái Cấu Trúc",
    "rarity": "rare",
    "descriptionVi": "Đổi các lá trong bộ bài bốc có giá trị nhỏ hơn 5 thành 6-9 ngẫu nhiên.",
    "price": 2,
    "artworkFrameIndex": 15,
    "image": "assets/cards/document/tai_cau_truc.webp"
  },
  {
    "id": "toi_uu_hoa",
    "type": "document",
    "nameVi": "Tối ưu hóa",
    "rarity": "rare",
    "descriptionVi": "Tăng giá trị lá mục tiêu thêm 1.",
    "price": 2,
    "artworkFrameIndex": 16,
    "image": "assets/cards/document/toi_uu_hoa.webp"
  },
  {
    "id": "copy",
    "type": "document",
    "nameVi": "Copy",
    "rarity": "epic",
    "descriptionVi": "Sao chép lá mục tiêu vào cuối bộ bài bốc.",
    "price": 4,
    "artworkFrameIndex": 17,
    "image": "assets/cards/document/copy.webp"
  },
  {
    "id": "may_man",
    "type": "decoration",
    "nameVi": "Trang Trí May Mắn",
    "rarity": "rare",
    "descriptionVi": "Lá được áp dụng: Khi đánh ra, có tỉ lệ nhận thêm <img src=\"assets/icons/coin.webp\" alt=\"Xu\" class=\"card-token-icon\" />. <span style=\"color: #ff9f43;\">(69%: +x/2 <img src=\"assets/icons/coin.webp\" alt=\"Xu\" class=\"card-token-icon\" />, 28%: +x <img src=\"assets/icons/coin.webp\" alt=\"Xu\" class=\"card-token-icon\" />, 3%: +2x <img src=\"assets/icons/coin.webp\" alt=\"Xu\" class=\"card-token-icon\" />)</span>",
    "price": 2,
    "decoType": "Lucky",
    "image": "assets/cards/decoration/may_man.webp"
  },
  {
    "id": "nhan",
    "type": "decoration",
    "nameVi": "Trang Trí Nhân",
    "rarity": "epic",
    "descriptionVi": "Lá được áp dụng: Khi đánh ra, x2 số <img src=\"assets/icons/coin.webp\" alt=\"Xu\" class=\"card-token-icon\" /> và <img src=\"assets/icons/bcoin.webp\" alt=\"Xu thưởng\" class=\"card-token-icon\" /> nhận được <span style=\"color: #ff9f43;\">(cộng dồn nhân 2 cho mỗi lá Nhân trước đó)</span>.",
    "price": 4,
    "decoType": "Multiply",
    "image": "assets/cards/decoration/nhan.webp"
  },
  {
    "id": "thep",
    "type": "decoration",
    "nameVi": "Trang Trí Thép",
    "rarity": "rare",
    "descriptionVi": "Lá được áp dụng: Khi giữ trên tay, x1.5 số <img src=\"assets/icons/coin.webp\" alt=\"Xu\" class=\"card-token-icon\" /> và <img src=\"assets/icons/bcoin.webp\" alt=\"Xu thưởng\" class=\"card-token-icon\" /> nhận được <span style=\"color: #c8f0a8;\">(tăng theo số lá Thép cầm trên tay)</span>.",
    "price": 2,
    "decoType": "Steel",
    "image": "assets/cards/decoration/thep.webp"
  },
  {
    "id": "kinh",
    "type": "decoration",
    "nameVi": "Trang Trí Kính",
    "rarity": "rare",
    "descriptionVi": "Lá được áp dụng: Khi đánh ra, x2 số <img src=\"assets/icons/coin.webp\" alt=\"Xu\" class=\"card-token-icon\" /> nhận được <span style=\"color: #ff4d4d;\">(có 33% cơ hội vỡ: chỉ nhận +1 <img src=\"assets/icons/coin.webp\" alt=\"Xu\" class=\"card-token-icon\" /> và mất trang trí Kính)</span>.",
    "price": 2,
    "decoType": "Glass",
    "image": "assets/cards/decoration/kinh.webp"
  },
  {
    "id": "hoang",
    "type": "decoration",
    "nameVi": "Trang Trí Hoang",
    "rarity": "common",
    "descriptionVi": "Lá được áp dụng: Được tính là tất cả các màu <span style=\"color: #ff9f43;\">(Đỏ, Lam, Lục, Vàng)</span> khi kết hợp chất.",
    "price": 1,
    "decoType": "Wild",
    "image": "assets/cards/decoration/hoang.webp"
  },
  {
    "id": "da",
    "type": "decoration",
    "nameVi": "Trang Trí Đá",
    "rarity": "epic",
    "descriptionVi": "Lá được áp dụng: Khi vừa ép trang trí, nhận ngay +2x <img src=\"assets/icons/coin.webp\" alt=\"Xu\" class=\"card-token-icon\" /> và +2x <img src=\"assets/icons/bcoin.webp\" alt=\"Xu thưởng\" class=\"card-token-icon\" /> <span style=\"color: #ff4d4d;\">(lá bài sẽ mất màu và không thể sửa đổi giá trị)</span>.",
    "price": 4,
    "decoType": "Stone",
    "image": "assets/cards/decoration/da.webp"
  },
  {
    "id": "vang",
    "type": "decoration",
    "nameVi": "Trang Trí Vàng",
    "rarity": "epic",
    "descriptionVi": "Lá được áp dụng: Khi giữ trên tay ở cuối lượt, nhận thêm +x/2 <img src=\"assets/icons/coin.webp\" alt=\"Xu\" class=\"card-token-icon\" />.",
    "price": 4,
    "decoType": "Gold",
    "image": "assets/cards/decoration/vang.webp"
  },
  {
    "id": "cong",
    "type": "decoration",
    "nameVi": "Trang Trí Cộng",
    "rarity": "rare",
    "descriptionVi": "Lá được áp dụng: Khi đánh ra, nhận thêm +x <img src=\"assets/icons/coin.webp\" alt=\"Xu\" class=\"card-token-icon\" />.",
    "price": 2,
    "decoType": "Plus",
    "image": "assets/cards/decoration/cong.webp"
  },
  {
    "id": "tui_mu",
    "type": "decoration",
    "nameVi": "Trang Trí Túi Mù",
    "rarity": "rare",
    "descriptionVi": "Lá được áp dụng: Biến thành 1 trang trí ngẫu nhiên <span style=\"color: #ff9f43;\">(60% Thường, 32% Cao cấp, 7% Cực phẩm, 1% Huyền thoại)</span> và xáo trở lại bộ bài bốc.",
    "price": 2,
    "decoType": "BlindBag",
    "image": "assets/cards/decoration/tui_mu.webp"
  },
  {
    "id": "hai_mat_1",
    "type": "decoration",
    "nameVi": "Hai Mặt 1",
    "rarity": "common",
    "descriptionVi": "Chứa giá trị 1 và giá trị gốc, tự chọn số gần mục tiêu nhất.",
    "price": 1,
    "decoType": "TwoSided_1",
    "image": "assets/cards/decoration/hai_mat_1.webp"
  },
  {
    "id": "hai_mat_2",
    "type": "decoration",
    "nameVi": "Hai Mặt 2",
    "rarity": "common",
    "descriptionVi": "Chứa giá trị 2 và giá trị gốc, tự chọn số gần mục tiêu nhất.",
    "price": 1,
    "decoType": "TwoSided_2",
    "image": "assets/cards/decoration/hai_mat_2.webp"
  },
  {
    "id": "hai_mat_3",
    "type": "decoration",
    "nameVi": "Hai Mặt 3",
    "rarity": "common",
    "descriptionVi": "Chứa giá trị 3 và giá trị gốc, tự chọn số gần mục tiêu nhất.",
    "price": 1,
    "decoType": "TwoSided_3",
    "image": "assets/cards/decoration/hai_mat_3.webp"
  },
  {
    "id": "hai_mat_4",
    "type": "decoration",
    "nameVi": "Hai Mặt 4",
    "rarity": "common",
    "descriptionVi": "Chứa giá trị 4 và giá trị gốc, tự chọn số gần mục tiêu nhất.",
    "price": 1,
    "decoType": "TwoSided_4",
    "image": "assets/cards/decoration/hai_mat_4.webp"
  },
  {
    "id": "hai_mat_5",
    "type": "decoration",
    "nameVi": "Hai Mặt 5",
    "rarity": "common",
    "descriptionVi": "Chứa giá trị 5 và giá trị gốc, tự chọn số gần mục tiêu nhất.",
    "price": 1,
    "decoType": "TwoSided_5",
    "image": "assets/cards/decoration/hai_mat_5.webp"
  },
  {
    "id": "hai_mat_6",
    "type": "decoration",
    "nameVi": "Hai Mặt 6",
    "rarity": "common",
    "descriptionVi": "Chứa giá trị 6 và giá trị gốc, tự chọn số gần mục tiêu nhất.",
    "price": 1,
    "decoType": "TwoSided_6",
    "image": "assets/cards/decoration/hai_mat_6.webp"
  },
  {
    "id": "hai_mat_7",
    "type": "decoration",
    "nameVi": "Hai Mặt 7",
    "rarity": "common",
    "descriptionVi": "Chứa giá trị 7 và giá trị gốc, tự chọn số gần mục tiêu nhất.",
    "price": 1,
    "decoType": "TwoSided_7",
    "image": "assets/cards/decoration/hai_mat_7.webp"
  },
  {
    "id": "hai_mat_8",
    "type": "decoration",
    "nameVi": "Hai Mặt 8",
    "rarity": "common",
    "descriptionVi": "Chứa giá trị 8 và giá trị gốc, tự chọn số gần mục tiêu nhất.",
    "price": 1,
    "decoType": "TwoSided_8",
    "image": "assets/cards/decoration/hai_mat_8.webp"
  },
  {
    "id": "hai_mat_9",
    "type": "decoration",
    "nameVi": "Hai Mặt 9",
    "rarity": "common",
    "descriptionVi": "Chứa giá trị 9 và giá trị gốc, tự chọn số gần mục tiêu nhất.",
    "price": 1,
    "decoType": "TwoSided_9",
    "image": "assets/cards/decoration/hai_mat_9.webp"
  },
  {
    "id": "kim_cuong",
    "type": "decoration",
    "nameVi": "Trang Trí Kim Cương",
    "rarity": "legendary",
    "descriptionVi": "Lá được áp dụng: Khi đánh ra, nhận ngay +1 <img src=\"assets/icons/point.webp\" alt=\"Điểm\" class=\"card-token-icon\" />.",
    "price": 8,
    "decoType": "Diamond",
    "image": "assets/cards/decoration/kim_cuong.webp"
  },
  {
    "id": "sticker_hidden",
    "type": "sticker",
    "nameVi": "Nhãn dán ẩn dấu",
    "rarity": "rare",
    "descriptionVi": "Không bị tính vào giới hạn bài trên tay khi bốc <span style=\"color: #c8f0a8;\">(tăng tối đa số lá có thể cầm)</span>.",
    "price": 2,
    "stickerType": "Hidden",
    "image": "assets/cards/sticker/sticker_hidden.webp"
  },
  {
    "id": "sticker_infinite",
    "type": "sticker",
    "nameVi": "Nhãn dán vô hạn",
    "rarity": "special",
    "descriptionVi": "Dùng vĩnh viễn. Khi đánh ra được hoàn ngay về tay <span style=\"color: #ff9f43;\">(không vào bài bỏ)</span>.",
    "price": 1,
    "stickerType": "Infinite",
    "image": "assets/cards/sticker/sticker_infinite.webp"
  },
  {
    "id": "sticker_durable",
    "type": "sticker",
    "nameVi": "Nhãn dán bền",
    "rarity": "common",
    "descriptionVi": "Khi đánh ra được hoàn về tay 1 lần <span style=\"color: #ff4d4d;\">(sau đó mất nhãn Bền)</span>.",
    "price": 1,
    "stickerType": "Durable",
    "image": "assets/cards/sticker/sticker_durable.webp"
  },
  {
    "id": "sticker_heavy",
    "type": "sticker",
    "nameVi": "Nhãn dán nặng",
    "rarity": "common",
    "descriptionVi": "Giá trị bài được tính <span style=\"color: #ff9f43;\">gấp đôi (x2)</span> giá trị gốc khi đánh ra.",
    "price": 1,
    "stickerType": "Heavy",
    "image": "assets/cards/sticker/sticker_heavy.webp"
  },
  {
    "id": "sticker_king",
    "type": "sticker",
    "nameVi": "Nhãn dán vua",
    "rarity": "rare",
    "descriptionVi": "Khi đánh ra, nhận 1 vật dụng miễn phí <span style=\"color: #c8f0a8;\">(0 <img src=\"assets/icons/coin.webp\" alt=\"Xu\" class=\"card-token-icon\" />)</span> ở Cửa hàng cùng vòng <span style=\"color: #ff9f43;\">(70% Thường, 20% Cao cấp, 9% Cực phẩm, 1% Huyền thoại)</span>.",
    "price": 2,
    "stickerType": "King",
    "image": "assets/cards/sticker/sticker_king.webp"
  },
  {
    "id": "sticker_send",
    "type": "sticker",
    "nameVi": "Nhãn dán gửi đi",
    "rarity": "epic",
    "descriptionVi": "Khi đánh ra, ép 1 trang trí ngẫu nhiên <span style=\"color: #ff9f43;\">(32% Thường, 50% Cao cấp, 17% Cực phẩm, 1% Huyền thoại)</span> và quay về bộ bốc <span style=\"color: #ff4d4d;\">(chỉ 1 lần)</span>.",
    "price": 4,
    "stickerType": "Send",
    "image": "assets/cards/sticker/sticker_send.webp"
  },
  {
    "id": "ke_khu_kho",
    "type": "event",
    "nameVi": "Sự kiện: Kẻ khù khờ",
    "rarity": "common",
    "descriptionVi": "Chỉ được phép sử dụng các dấu +, -, x, : và các số từ 1 đến 9.",
    "price": 0,
    "image": "assets/cards/event/ke_khu_kho.webp"
  },
  {
    "id": "mot_sach",
    "type": "event",
    "nameVi": "Sự kiện: Mọt sách",
    "rarity": "common",
    "descriptionVi": "Không được phép sử dụng các dấu +, -, x, : và các số từ 1 đến 9.",
    "price": 0,
    "image": "assets/cards/event/mot_sach.webp"
  },
  {
    "id": "tu_duy_nguoc",
    "type": "event",
    "nameVi": "Sự kiện: Tư duy ngược",
    "rarity": "common",
    "descriptionVi": "Win bằng cách xa giá trị yêu cầu nhất có thể.",
    "price": 0,
    "image": "assets/cards/event/tu_duy_nguoc.webp"
  },
  {
    "id": "loi_nhi_phan",
    "type": "event",
    "nameVi": "Sự kiện: Lỗi",
    "rarity": "common",
    "descriptionVi": "Giá trị cần đạt được sẽ hiển thị dưới dạng mã nhị phân.",
    "price": 0,
    "image": "assets/cards/event/loi_nhi_phan.webp"
  },
  {
    "id": "troi_mua",
    "type": "event",
    "nameVi": "Sự kiện: Trời mưa",
    "rarity": "rare",
    "descriptionVi": "Trang trí sẽ không thể hoạt động.",
    "price": 0,
    "image": "assets/cards/event/troi_mua.webp"
  },
  {
    "id": "mua_nang",
    "type": "event",
    "nameVi": "Sự kiện: Mưa nặng",
    "rarity": "rare",
    "descriptionVi": "Lá vật phẩm sẽ không thể hoạt động.",
    "price": 0,
    "image": "assets/cards/event/mua_nang.webp"
  },
  {
    "id": "mua_da",
    "type": "event",
    "nameVi": "Sự kiện: Mưa đá",
    "rarity": "rare",
    "descriptionVi": "Giá trị của toàn bộ lá hỗ trợ trên sân -20%.",
    "price": 0,
    "image": "assets/cards/event/mua_da.webp"
  },
  {
    "id": "suong_mu",
    "type": "event",
    "nameVi": "Sự kiện: Sương mù",
    "rarity": "rare",
    "descriptionVi": "Các lá bài giá trị sẽ không mang bất kì màu gì.",
    "price": 0,
    "image": "assets/cards/event/suong_mu.webp"
  },
  {
    "id": "dong_dat",
    "type": "event",
    "nameVi": "Sự kiện: Động đất",
    "rarity": "rare",
    "descriptionVi": "Đảo lộn vị trí các lá hỗ trợ của bạn.",
    "price": 0,
    "image": "assets/cards/event/dong_dat.webp"
  },
  {
    "id": "nhieu_loan",
    "type": "event",
    "nameVi": "Sự kiện: Nhiễu loạn",
    "rarity": "epic",
    "descriptionVi": "Thay vào các ô hỗ trợ bằng vật phẩm bất kì trong 1 lượt.",
    "price": 0,
    "image": "assets/cards/event/nhieu_loan.webp"
  },
  {
    "id": "nguyen_rua",
    "type": "event",
    "nameVi": "Sự kiện: Nguyền rủa",
    "rarity": "legendary",
    "descriptionVi": "Nguyền rủa 1 lá hỗ trợ. Nếu kích hoạt, nhận khóa học Lời nguyền.",
    "price": 0,
    "image": "assets/cards/event/nguyen_rua.webp"
  },
  {
    "id": "lam_phat",
    "type": "event",
    "nameVi": "Sự kiện: Lạm phát",
    "rarity": "rare",
    "descriptionVi": "Shop sẽ đắt gấp đôi.",
    "price": 0,
    "image": "assets/cards/event/lam_phat.webp"
  },
  {
    "id": "suy_thoai",
    "type": "event",
    "nameVi": "Sự kiện: Suy thoái",
    "rarity": "epic",
    "descriptionVi": "Hệ số nhân coin giảm một nửa.",
    "price": 0,
    "image": "assets/cards/event/suy_thoai.webp"
  },
  {
    "id": "pack_itemi_common",
    "type": "pack",
    "nameVi": "Gói Vật Phẩm I (Thường)",
    "rarity": "common",
    "descriptionVi": "Mở 3 lá, được chọn 1 lá.",
    "price": 2,
    "frameIndex": 0,
    "image": "assets/cards/pack/pack_itemi_common.webp"
  },
  {
    "id": "pack_itemi_rare",
    "type": "pack",
    "nameVi": "Gói Vật Phẩm I (Cao cấp)",
    "rarity": "rare",
    "descriptionVi": "Mở 3 lá, được chọn 1 lá.",
    "price": 3,
    "frameIndex": 1,
    "image": "assets/cards/pack/pack_itemi_rare.webp"
  },
  {
    "id": "pack_itemi_epic",
    "type": "pack",
    "nameVi": "Gói Vật Phẩm I (Cực phẩm)",
    "rarity": "epic",
    "descriptionVi": "Mở 5 lá, được chọn 2 lá.",
    "price": 5,
    "frameIndex": 2,
    "image": "assets/cards/pack/pack_itemi_epic.webp"
  },
  {
    "id": "pack_itemi_legendary",
    "type": "pack",
    "nameVi": "Gói Vật Phẩm I (Huyền thoại)",
    "rarity": "legendary",
    "descriptionVi": "Mở 5 lá, được chọn 2 lá.",
    "price": 9,
    "frameIndex": 3,
    "image": "assets/cards/pack/pack_itemi_legendary.webp"
  },
  {
    "id": "pack_itemii_common",
    "type": "pack",
    "nameVi": "Gói Vật Phẩm II (Thường)",
    "rarity": "common",
    "descriptionVi": "Mở 3 lá, được chọn 2 lá.",
    "price": 3,
    "frameIndex": 4,
    "image": "assets/cards/pack/pack_itemii_common.webp"
  },
  {
    "id": "pack_itemii_rare",
    "type": "pack",
    "nameVi": "Gói Vật Phẩm II (Cao cấp)",
    "rarity": "rare",
    "descriptionVi": "Mở 3 lá, được chọn 2 lá.",
    "price": 4,
    "frameIndex": 5,
    "image": "assets/cards/pack/pack_itemii_rare.webp"
  },
  {
    "id": "pack_itemii_epic",
    "type": "pack",
    "nameVi": "Gói Vật Phẩm II (Cực phẩm)",
    "rarity": "epic",
    "descriptionVi": "Mở 5 lá, được chọn 3 lá.",
    "price": 6,
    "frameIndex": 6,
    "image": "assets/cards/pack/pack_itemii_epic.webp"
  },
  {
    "id": "pack_itemii_legendary",
    "type": "pack",
    "nameVi": "Gói Vật Phẩm II (Huyền thoại)",
    "rarity": "legendary",
    "descriptionVi": "Mở 5 lá, được chọn 3 lá.",
    "price": 10,
    "frameIndex": 7,
    "image": "assets/cards/pack/pack_itemii_legendary.webp"
  },
  {
    "id": "pack_stickeri_common",
    "type": "pack",
    "nameVi": "Gói Nhãn Dán I (Thường)",
    "rarity": "common",
    "descriptionVi": "Mở 3 lá, được chọn 1 lá.",
    "price": 2,
    "frameIndex": 8,
    "image": "assets/cards/pack/pack_stickeri_common.webp"
  },
  {
    "id": "pack_stickeri_rare",
    "type": "pack",
    "nameVi": "Gói Nhãn Dán I (Cao cấp)",
    "rarity": "rare",
    "descriptionVi": "Mở 3 lá, được chọn 1 lá.",
    "price": 3,
    "frameIndex": 9,
    "image": "assets/cards/pack/pack_stickeri_rare.webp"
  },
  {
    "id": "pack_stickeri_epic",
    "type": "pack",
    "nameVi": "Gói Nhãn Dán I (Cực phẩm)",
    "rarity": "epic",
    "descriptionVi": "Mở 5 lá, được chọn 2 lá.",
    "price": 5,
    "frameIndex": 10,
    "image": "assets/cards/pack/pack_stickeri_epic.webp"
  },
  {
    "id": "pack_stickeri_legendary",
    "type": "pack",
    "nameVi": "Gói Nhãn Dán I (Huyền thoại)",
    "rarity": "legendary",
    "descriptionVi": "Mở 5 lá, được chọn 2 lá.",
    "price": 9,
    "frameIndex": 11,
    "image": "assets/cards/pack/pack_stickeri_legendary.webp"
  },
  {
    "id": "pack_stickerii_common",
    "type": "pack",
    "nameVi": "Gói Nhãn Dán II (Thường)",
    "rarity": "common",
    "descriptionVi": "Mở 3 lá, được chọn 2 lá.",
    "price": 3,
    "frameIndex": 12,
    "image": "assets/cards/pack/pack_stickerii_common.webp"
  },
  {
    "id": "pack_stickerii_rare",
    "type": "pack",
    "nameVi": "Gói Nhãn Dán II (Cao cấp)",
    "rarity": "rare",
    "descriptionVi": "Mở 3 lá, được chọn 2 lá.",
    "price": 4,
    "frameIndex": 13,
    "image": "assets/cards/pack/pack_stickerii_rare.webp"
  },
  {
    "id": "pack_stickerii_epic",
    "type": "pack",
    "nameVi": "Gói Nhãn Dán II (Cực phẩm)",
    "rarity": "epic",
    "descriptionVi": "Mở 5 lá, được chọn 3 lá.",
    "price": 6,
    "frameIndex": 14,
    "image": "assets/cards/pack/pack_stickerii_epic.webp"
  },
  {
    "id": "pack_stickerii_legendary",
    "type": "pack",
    "nameVi": "Gói Nhãn Dán II (Huyền thoại)",
    "rarity": "legendary",
    "descriptionVi": "Mở 5 lá, được chọn 3 lá.",
    "price": 10,
    "frameIndex": 15,
    "image": "assets/cards/pack/pack_stickerii_legendary.webp"
  },
  {
    "id": "pack_decorationi_common",
    "type": "pack",
    "nameVi": "Gói Trang Trí I (Thường)",
    "rarity": "common",
    "descriptionVi": "Mở 3 lá, được chọn 1 lá.",
    "price": 2,
    "frameIndex": 16,
    "image": "assets/cards/pack/pack_decorationi_common.webp"
  },
  {
    "id": "pack_decorationi_rare",
    "type": "pack",
    "nameVi": "Gói Trang Trí I (Cao cấp)",
    "rarity": "rare",
    "descriptionVi": "Mở 3 lá, được chọn 1 lá.",
    "price": 3,
    "frameIndex": 17,
    "image": "assets/cards/pack/pack_decorationi_rare.webp"
  },
  {
    "id": "pack_decorationi_epic",
    "type": "pack",
    "nameVi": "Gói Trang Trí I (Cực phẩm)",
    "rarity": "epic",
    "descriptionVi": "Mở 5 lá, được chọn 2 lá.",
    "price": 5,
    "frameIndex": 18,
    "image": "assets/cards/pack/pack_decorationi_epic.webp"
  },
  {
    "id": "pack_decorationi_legendary",
    "type": "pack",
    "nameVi": "Gói Trang Trí I (Huyền thoại)",
    "rarity": "legendary",
    "descriptionVi": "Mở 5 lá, được chọn 2 lá.",
    "price": 9,
    "frameIndex": 19,
    "image": "assets/cards/pack/pack_decorationi_legendary.webp"
  },
  {
    "id": "pack_decorationii_common",
    "type": "pack",
    "nameVi": "Gói Trang Trí II (Thường)",
    "rarity": "common",
    "descriptionVi": "Mở 3 lá, được chọn 2 lá.",
    "price": 3,
    "frameIndex": 20,
    "image": "assets/cards/pack/pack_decorationii_common.webp"
  },
  {
    "id": "pack_decorationii_rare",
    "type": "pack",
    "nameVi": "Gói Trang Trí II (Cao cấp)",
    "rarity": "rare",
    "descriptionVi": "Mở 3 lá, được chọn 2 lá.",
    "price": 4,
    "frameIndex": 21,
    "image": "assets/cards/pack/pack_decorationii_rare.webp"
  },
  {
    "id": "pack_decorationii_epic",
    "type": "pack",
    "nameVi": "Gói Trang Trí II (Cực phẩm)",
    "rarity": "epic",
    "descriptionVi": "Mở 5 lá, được chọn 3 lá.",
    "price": 6,
    "frameIndex": 22,
    "image": "assets/cards/pack/pack_decorationii_epic.webp"
  },
  {
    "id": "pack_decorationii_legendary",
    "type": "pack",
    "nameVi": "Gói Trang Trí II (Huyền thoại)",
    "rarity": "legendary",
    "descriptionVi": "Mở 5 lá, được chọn 3 lá.",
    "price": 10,
    "frameIndex": 23,
    "image": "assets/cards/pack/pack_decorationii_legendary.webp"
  },
  {
    "id": "pack_documenti_common",
    "type": "pack",
    "nameVi": "Gói Tài Liệu I (Thường)",
    "rarity": "common",
    "descriptionVi": "Mở 3 lá, được chọn 1 lá.",
    "price": 2,
    "frameIndex": 24,
    "image": "assets/cards/pack/pack_documenti_common.webp"
  },
  {
    "id": "pack_documenti_rare",
    "type": "pack",
    "nameVi": "Gói Tài Liệu I (Cao cấp)",
    "rarity": "rare",
    "descriptionVi": "Mở 3 lá, được chọn 1 lá.",
    "price": 3,
    "frameIndex": 25,
    "image": "assets/cards/pack/pack_documenti_rare.webp"
  },
  {
    "id": "pack_documenti_epic",
    "type": "pack",
    "nameVi": "Gói Tài Liệu I (Cực phẩm)",
    "rarity": "epic",
    "descriptionVi": "Mở 5 lá, được chọn 2 lá.",
    "price": 5,
    "frameIndex": 26,
    "image": "assets/cards/pack/pack_documenti_epic.webp"
  },
  {
    "id": "pack_documenti_legendary",
    "type": "pack",
    "nameVi": "Gói Tài Liệu I (Huyền thoại)",
    "rarity": "legendary",
    "descriptionVi": "Mở 5 lá, được chọn 2 lá.",
    "price": 9,
    "frameIndex": 27,
    "image": "assets/cards/pack/pack_documenti_legendary.webp"
  },
  {
    "id": "pack_documentii_common",
    "type": "pack",
    "nameVi": "Gói Tài Liệu II (Thường)",
    "rarity": "common",
    "descriptionVi": "Mở 3 lá, được chọn 2 lá.",
    "price": 3,
    "frameIndex": 28,
    "image": "assets/cards/pack/pack_documentii_common.webp"
  },
  {
    "id": "pack_documentii_rare",
    "type": "pack",
    "nameVi": "Gói Tài Liệu II (Cao cấp)",
    "rarity": "rare",
    "descriptionVi": "Mở 3 lá, được chọn 2 lá.",
    "price": 4,
    "frameIndex": 29,
    "image": "assets/cards/pack/pack_documentii_rare.webp"
  },
  {
    "id": "pack_documentii_epic",
    "type": "pack",
    "nameVi": "Gói Tài Liệu II (Cực phẩm)",
    "rarity": "epic",
    "descriptionVi": "Mở 5 lá, được chọn 3 lá.",
    "price": 6,
    "frameIndex": 30,
    "image": "assets/cards/pack/pack_documentii_epic.webp"
  },
  {
    "id": "pack_documentii_legendary",
    "type": "pack",
    "nameVi": "Gói Tài Liệu II (Huyền thoại)",
    "rarity": "legendary",
    "descriptionVi": "Mở 5 lá, được chọn 3 lá.",
    "price": 10,
    "frameIndex": 31,
    "image": "assets/cards/pack/pack_documentii_legendary.webp"
  },
  {
    "id": "pack_valuei_common",
    "type": "pack",
    "nameVi": "Gói Số I (Thường)",
    "rarity": "common",
    "descriptionVi": "Mở 3 lá, được chọn 3 lá.",
    "price": 2,
    "frameIndex": 32,
    "image": "assets/cards/pack/pack_valuei_common.webp"
  },
  {
    "id": "pack_valuei_rare",
    "type": "pack",
    "nameVi": "Gói Số I (Cao cấp)",
    "rarity": "rare",
    "descriptionVi": "Mở 5 lá, được chọn 5 lá.",
    "price": 3,
    "frameIndex": 33,
    "image": "assets/cards/pack/pack_valuei_rare.webp"
  },
  {
    "id": "pack_valuei_epic",
    "type": "pack",
    "nameVi": "Gói Số I (Cực phẩm)",
    "rarity": "epic",
    "descriptionVi": "Mở 5 lá, được chọn 5 lá.",
    "price": 5,
    "frameIndex": 34,
    "image": "assets/cards/pack/pack_valuei_epic.webp"
  },
  {
    "id": "pack_valuei_legendary",
    "type": "pack",
    "nameVi": "Gói Số I (Huyền thoại)",
    "rarity": "legendary",
    "descriptionVi": "Mở 5 lá, được chọn 5 lá.",
    "price": 9,
    "frameIndex": 35,
    "image": "assets/cards/pack/pack_valuei_legendary.webp"
  },
  {
    "id": "pack_valueii_common",
    "type": "pack",
    "nameVi": "Gói Số II (Thường)",
    "rarity": "common",
    "descriptionVi": "Mở 3 lá, được chọn 3 lá.",
    "price": 2,
    "frameIndex": 36,
    "image": "assets/cards/pack/pack_valueii_common.webp"
  },
  {
    "id": "pack_valueii_rare",
    "type": "pack",
    "nameVi": "Gói Số II (Cao cấp)",
    "rarity": "rare",
    "descriptionVi": "Mở 5 lá, được chọn 5 lá.",
    "price": 3,
    "frameIndex": 37,
    "image": "assets/cards/pack/pack_valueii_rare.webp"
  },
  {
    "id": "pack_valueii_epic",
    "type": "pack",
    "nameVi": "Gói Số II (Cực phẩm)",
    "rarity": "epic",
    "descriptionVi": "Mở 5 lá, được chọn 5 lá.",
    "price": 5,
    "frameIndex": 38,
    "image": "assets/cards/pack/pack_valueii_epic.webp"
  },
  {
    "id": "pack_valueii_legendary",
    "type": "pack",
    "nameVi": "Gói Số II (Huyền thoại)",
    "rarity": "legendary",
    "descriptionVi": "Mở 6 lá, được chọn 6 lá.",
    "price": 9,
    "frameIndex": 39,
    "image": "assets/cards/pack/pack_valueii_legendary.webp"
  },
  {
    "id": "pack_valueiii_epic",
    "type": "pack",
    "nameVi": "Gói Số III (Cực phẩm)",
    "rarity": "epic",
    "descriptionVi": "Mở 5 lá, được chọn 5 lá.",
    "price": 1,
    "frameIndex": 40,
    "image": "assets/cards/pack/pack_valueiii_epic.webp"
  },
  {
    "id": "pack_valueiii_legendary",
    "type": "pack",
    "nameVi": "Gói Số III (Huyền thoại)",
    "rarity": "legendary",
    "descriptionVi": "Mở 5 lá, được chọn 5 lá.",
    "price": 2,
    "frameIndex": 41,
    "image": "assets/cards/pack/pack_valueiii_legendary.webp"
  },
  {
    "id": "pack_operator_common",
    "type": "pack",
    "nameVi": "Gói Phép Tính (Thường)",
    "rarity": "common",
    "descriptionVi": "Mở 3 lá, được chọn 1 lá.",
    "price": 2,
    "frameIndex": 42,
    "image": "assets/cards/pack/pack_operator_common.webp"
  },
  {
    "id": "pack_operator_rare",
    "type": "pack",
    "nameVi": "Gói Phép Tính (Cao cấp)",
    "rarity": "rare",
    "descriptionVi": "Mở 3 lá, được chọn 1 lá.",
    "price": 3,
    "frameIndex": 43,
    "image": "assets/cards/pack/pack_operator_rare.webp"
  },
  {
    "id": "pack_operator_epic",
    "type": "pack",
    "nameVi": "Gói Phép Tính (Cực phẩm)",
    "rarity": "epic",
    "descriptionVi": "Mở 5 lá, được chọn 2 lá.",
    "price": 5,
    "frameIndex": 44,
    "image": "assets/cards/pack/pack_operator_epic.webp"
  },
  {
    "id": "pack_operatorlevel1_common",
    "type": "pack",
    "nameVi": "Gói Phép Tính Cấp I (Thường)",
    "rarity": "common",
    "descriptionVi": "Mở 3 lá, được chọn 1 lá.",
    "price": 2,
    "frameIndex": 45,
    "image": "assets/cards/pack/pack_operatorlevel1_common.webp"
  },
  {
    "id": "pack_operatorlevel1_rare",
    "type": "pack",
    "nameVi": "Gói Phép Tính Cấp I (Cao cấp)",
    "rarity": "rare",
    "descriptionVi": "Mở 5 lá, được chọn 2 lá.",
    "price": 3,
    "frameIndex": 46,
    "image": "assets/cards/pack/pack_operatorlevel1_rare.webp"
  }
];
